import type { Moment } from '../shared/types'
import { s } from './helpers'

// Market moments, batch 5. Prices and IV figures are approximate, reconstructed for teaching (as traded at the time).
// Prices are as traded at the time (not adjusted for later splits: SMCI 10:1 Oct 2024; AVGO prices are after its 10:1 split of Jul 2024).
export const MOMENTS_B5: Moment[] = [
  {
    id: 'biib-2019-03', ticker: 'BIIB', title: 'The aducanumab futility stop', date: 'Mar 2019',
    summary: 'A futility analysis ended two Phase 3 Alzheimer\'s trials before the open; BIIB fell ≈ 29% in one day.',
    terms: ['gap', 'tail-risk', 'position-sizing', 'stop-loss', 'cash-secured-put'], tags: ['biotech', 'binary', 'gap'],
    checkpoints: [
      { label: 'Before the news', date: '2019-03-20', context: 'BIIB ≈ $321. Much of the bull case rests on aducanumab, in two Phase 3 trials (ENGAGE, EMERGE). An interim futility check is due; the date is not public.',
        step: s('BIIB is a large part of your portfolio. How do you manage a one-drug risk with no known date?', [['size', 'Cut to a size you can lose in a gap, or buy puts'], ['stop', 'Rely on a stop-loss 10% below'], ['add', 'Add more, Phase 3 drugs usually work']], 'size', 'Trial news comes before the open and gaps the stock. A stop fills far below its level; only size or a put limits the loss.') },
      { label: 'Trials halted', date: '2019-03-21', context: 'Biogen and Eisai stop both trials: unlikely to meet the primary endpoint. BIIB opened ≈ $230, closed ≈ $227 (−29%). Worst day since 2005.',
        step: s('Last month you sold a cash-secured put at the $300 strike for a small credit. Where do you stand?', [['deep', 'Down ≈ $73 a share less the credit, and likely assigned'], ['credit', 'The loss is limited to the credit']], 'deep', 'A short put loses strike minus price minus credit. Selling premium on a one-drug biotech carries the full gap risk.') },
      { label: 'The revival', date: '2019-10-22', context: 'Biogen says a larger dataset shows EMERGE met its endpoint and plans an FDA filing. BIIB ≈ $224 → ≈ $282 (+26%).',
        step: s('Puts bought in March lost value on this day. What does the year teach?', [['both', 'One-drug biotech gaps both ways: small size, defined risk'], ['chart', 'Chart patterns could have predicted both moves']], 'both', 'Neither gap was in the price chart. Plan for both directions instead of betting on one.') },
    ],
    outcome: 'Two [[gap]]s of ≈ 26–29% in seven months, both on unscheduled news. [[position-sizing]] mattered more than any forecast.',
  },
  {
    id: 'biib-2021-06', ticker: 'BIIB', title: 'The Aduhelm approval', date: 'Jun 2021',
    summary: 'The FDA approved aducanumab against its advisers\' vote; BIIB jumped ≈ 38% and touched ≈ $468 intraday.',
    terms: ['iv', 'iv-crush', 'debit-spread', 'short-straddle', 'covered-call'], tags: ['biotech', 'fda', 'binary'],
    checkpoints: [
      { label: 'Adviser vote', date: '2020-11-09', context: 'Nov 4: positive FDA briefing papers, BIIB +44% to ≈ $356. Nov 6: the advisory panel votes against the drug; trading halted. Nov 9: closed ≈ $236 (−28%).',
        step: s('BIIB moved +44%, then −28%, in three sessions. What will options cost into the final FDA decision?', [['rich', 'IV stays very high: the market prices a huge binary move'], ['cheap', 'Options get cheap, the news is out']], 'rich', 'The final decision is still binary. Option sellers demand a big premium for that gap risk.') },
      { label: 'Day before the decision', date: '2021-06-04', context: 'FDA decision due Jun 7. BIIB ≈ $286. Most analysts expect a rejection after the panel vote. Short-dated IV is very high (approximate).',
        step: s('You think the market is too gloomy but cannot know the result. Which trade fits?', [['spread', 'Small call debit spread: defined risk, less exposed to the IV drop'], ['straddle', 'Sell a naked straddle to collect the rich IV'], ['margin', 'Buy shares on margin']], 'spread', 'The short leg offsets part of the IV crush and lowers the cost. A naked straddle loses big on any large move.') },
      { label: 'Approval day', date: '2021-06-07', context: 'Accelerated approval. BIIB opened ≈ $295, hit ≈ $468, closed ≈ $396 (+38%). IV still elevated after the event.',
        step: s('You own BIIB from below $300. How can you take income from the still-high IV?', [['cc', 'Sell an OTM covered call'], ['calls', 'Buy more calls at this IV']], 'cc', 'After the event, the stock gave back much of the spike. A covered call sells rich IV against shares you already hold.') },
    ],
    outcome: 'A pure binary that went up. By Jan 2022 BIIB was ≈ $225 after Medicare proposed limited coverage. [[iv-crush]] and fading hype favoured sellers of [[covered-call]]s.',
  },
  {
    id: 'zm-2020-11', ticker: 'ZM', title: 'The vaccine rotation', date: 'Nov 2020',
    summary: 'Pfizer–BioNTech\'s 90% efficacy result lifted the market but sank stay-at-home stocks; ZM fell ≈ 17% in a day.',
    terms: ['correlation', 'beta-weighting', 'protective-put', 'gap', 'hedging'], tags: ['rotation', 'biotech', 'macro'],
    checkpoints: [
      { label: 'Election week', date: '2020-11-06', context: 'ZM ≈ $500, up from ≈ $68 at the start of 2020. Your tech portfolio is heavy in stay-at-home names. Vaccine data could come any week.',
        step: s('Which hedge matches the real risk in this portfolio?', [['basket', 'Puts on the stay-at-home names you hold'], ['spy', 'SPY puts'], ['none', 'No hedge, these are growth leaders']], 'basket', 'Good vaccine news helps the index but hurts this factor. Hedge the exposure you hold, not the whole market.') },
      { label: 'The readout', date: '2020-11-09', context: 'Pfizer: > 90% efficacy at interim. PFE opened ≈ +15%, closed ≈ +8%. SPY +1.3%. ZM ≈ $500 → ≈ $413 (−17%), its worst day on record.',
        step: s('You held ZM with a $450 protective put. What did the gap do to your position?', [['floor', 'Below $450 the put gains about $1 for each $1 the stock falls'], ['expiry', 'The put only helps at expiry']], 'floor', 'A long put gains value as soon as the stock falls below the strike. You can sell it any day; you do not have to wait for expiry.') },
      { label: 'Second vaccine', date: '2020-11-16', context: 'Moderna reports ≈ 94.5% efficacy. ZM ≈ $399, down ≈ 20% from Nov 6. PFE has given back most of its Nov 9 jump.',
        step: s('Short-dated PFE calls bought on Nov 9 lost value. Why?', [['priced', 'The news was priced in at the open; the follow-through was in the rotation'], ['bad', 'The vaccine data turned out bad']], 'priced', 'A known positive is priced fast. The bigger, slower move was money leaving the stay-at-home trade.') },
    ],
    outcome: 'One headline moved two groups in opposite directions. [[correlation]] inside the basket mattered more than the index, so a [[beta-weighting]] view against SPY missed the risk.',
  },
  {
    id: 'atvi-2022-01', ticker: 'ATVI', title: 'Microsoft buys Activision', date: 'Jan 2022',
    summary: 'Microsoft agreed to pay $95 cash; ATVI jumped ≈ 26% to ≈ $82 but kept a wide spread through 21 months of antitrust fights.',
    terms: ['risk-reward', 'expected-value', 'tail-risk', 'protective-put', 'covered-call'], tags: ['merger', 'arbitrage', 'regulation'],
    checkpoints: [
      { label: 'Deal day', date: '2022-01-18', context: '$95 a share in cash (≈ $68.7B). ATVI ≈ $65 → ≈ $82.31 (+26%). Spread ≈ $12.70 (≈ 15%). MSFT −2.4%.',
        step: s('A 15% spread on an all-cash deal is wide. What does it say?', [['risk', 'The market prices a real chance of a break back toward $65'], ['free', 'It is free money: the deal is signed']], 'risk', 'Gain ≈ $13 if it closes, loss ≈ $17 if it breaks. The spread is the price of that risk.') },
      { label: 'UK blocks', date: '2023-04-26', context: 'The FTC sued in Dec 2022. Now the UK CMA blocks the deal. ATVI fell ≈ 11% to ≈ $77 intraday.',
        step: s('You hold ATVI as a merger-arb trade. What would have capped the break risk?', [['put', 'A put near the pre-deal price, bought at entry'], ['nput', 'Selling more naked puts for yield']], 'put', 'Arb returns are small and the break loss is large. A put turns that tail into a known cost.') },
      { label: 'Court clears', date: '2023-07-11', context: 'A US judge denies the FTC injunction. ATVI closed +10%, high ≈ $92.91. Spread now ≈ $2–3.',
        step: s('ATVI is ≈ $92 and the deal pays $95. Best way to add return?', [['cc', 'Sell calls near $95: gains above $95 are unlikely'], ['calls', 'Buy calls for more upside']], 'cc', 'The deal price caps the upside. Calls above $95 need a rival bid, so selling them earns premium for little lost upside.') },
    ],
    outcome: 'Closed at $95 on Oct 13 2023 after a revised cloud-gaming deal satisfied the UK. Arbs earned the spread, but only after an ≈ 11% [[tail-risk]] scare.',
  },
  {
    id: 'twtr-2022-04', ticker: 'TWTR', title: 'Musk buys Twitter, eventually', date: 'Apr–Oct 2022',
    summary: 'Musk agreed to pay $54.20, tried to walk away, then closed; the spread swung from ≈ 5% to ≈ 40% of the deal price.',
    terms: ['risk-reward', 'position-sizing', 'bull-call-spread', 'iv-crush', 'tail-risk'], tags: ['merger', 'arbitrage', 'event'],
    checkpoints: [
      { label: 'Deal signed', date: '2022-04-25', context: 'Musk\'s 9.2% stake (Apr 4) lifted TWTR 27% to ≈ $49.97 from ≈ $39. Now a $54.20 cash deal (≈ $44B). Closed ≈ $51.70.',
        step: s('Spread ≈ $2.50. A break could send TWTR back to ≈ $39. How do you size the arb?', [['small', 'Small: you risk ≈ $13 to make ≈ $2.50'], ['big', 'Large: a signed deal always closes']], 'small', 'Risk-reward is about 5 to 1 against you. Size for the break, not for the spread.') },
      { label: 'Musk walks', date: '2022-07-11', context: 'May 13: deal "on hold", −9.7%. Jul 8: Musk sends a termination notice. Jul 11: closed ≈ $32.65 (−11%). Twitter sues in Delaware on Jul 12.',
        step: s('Spread ≈ $21.50. You think Twitter wins in court. Which structure fits?', [['cs', 'Small bull call spread, defined cost'], ['margin', 'Shares on margin'], ['nput', 'Sell naked puts in size']], 'cs', 'A court case is binary. The call spread caps the loss if Musk wins and still pays well if he loses.') },
      { label: 'Musk relents', date: '2022-10-04', context: 'Musk offers to close at $54.20. Trading halted twice. TWTR closed ≈ $52.00 (+22%).',
        step: s('The stock is now pinned near $54.20. What happens to TWTR option IV?', [['fall', 'It collapses: the deal price caps the range'], ['rise', 'It rises on the news']], 'fall', 'A near-certain cash deal leaves little room to move. Long options lose their time value fast.') },
    ],
    outcome: 'Closed Oct 27 2022 at $54.20. Arbs who sized for the break survived the ≈ 40% scare; a [[bull-call-spread]] was a defined-risk bet on the court.',
  },
  {
    id: 'lnkd-2016-06', ticker: 'LNKD', title: 'Microsoft buys LinkedIn', date: 'Jun 2016',
    summary: 'A $196-a-share cash deal lifted LNKD ≈ 47% in a day, from $131.08 to ≈ $192.',
    terms: ['covered-call', 'iv-crush', 'extrinsic', 'intrinsic', 'gap'], tags: ['merger', 'tech', 'gap'],
    checkpoints: [
      { label: 'Friday close', date: '2016-06-10', context: 'LNKD $131.08, far below its 2015 highs after a guidance shock in February. You own shares and sell $140 calls each month.',
        step: s('What risk does your monthly covered call carry?', [['cap', 'A surprise bid jumps past $140; you keep only the premium above it'], ['none', 'None, you keep the premium either way']], 'cap', 'A covered call trades upside for income. A takeover gap is exactly the upside you sold.') },
      { label: 'Deal day', date: '2016-06-13', context: 'Microsoft offers $196 cash ($26.2B). LNKD closed ≈ $192.21 (+47%). MSFT −2.6%. Spread ≈ $3.80 (≈ 2%).',
        step: s('A friend held a $140 call. IV collapsed after the deal. What is it worth?', [['intr', 'About intrinsic, ≈ $52; little time value left'], ['more', 'Well above intrinsic, IV went up']], 'intr', 'A stock pinned near a cash price has little left to move. Extrinsic value drains fast.') },
      { label: 'Approvals', date: '2016-12-07', context: 'The EU approved the deal Dec 6; closing is set for Dec 8. LNKD trades just under $196.',
        step: s('You hold LNKD near $195. Are $200 calls a cheap upside bet?', [['no', 'No: above $196 needs a rival bid that did not come'], ['yes', 'Yes, takeover stocks keep rising']], 'no', 'The deal price is a ceiling. OTM calls above it are a bet on a new bidder only.') },
    ],
    outcome: 'Closed Dec 8 2016 at $196. Covered-call writers missed most of the [[gap]]; call holders kept the [[intrinsic]] but lost the [[extrinsic]] value.',
  },
  {
    id: 'wfm-2017-06', ticker: 'WFM', title: 'Amazon buys Whole Foods', date: 'Jun 2017',
    summary: 'Amazon\'s $42 cash deal lifted WFM ≈ 29% and above the offer; other grocers fell.',
    terms: ['collar', 'correlation', 'gap', 'risk-reward', 'iv'], tags: ['merger', 'retail', 'contagion'],
    checkpoints: [
      { label: 'Kroger cuts outlook', date: '2017-06-15', context: 'KR fell ≈ 19% to ≈ $24.56 after a profit-outlook cut. WFM ≈ $33. Put IV on grocers jumps.',
        step: s('You own KR and want to keep it, but limit the next loss. Put IV is high. Best structure?', [['collar', 'A collar: buy a put, sell a call to pay for it'], ['atm', 'Buy ATM puts at any price'], ['none', 'No hedge, the bad news is out']], 'collar', 'High IV makes calls rich to sell. The call pays for the put, so the floor costs little.') },
      { label: 'Deal day', date: '2017-06-16', context: 'Amazon offers $42 cash ($13.7B). WFM closed $42.68, above the offer, on hopes of a rival bid. KR −9.2%, COST −7.2%, AMZN +2.4%.',
        step: s('WFM trades above $42. What is the market pricing?', [['bid', 'A chance of a higher bid; if none comes, it drifts to $42'], ['sure', 'A sure gain for buyers at $42.68']], 'bid', 'A negative spread is a bet on a better offer. With no rival, the stock converts at $42.') },
      { label: 'Cleared', date: '2017-08-23', context: 'The FTC cleared the deal. No rival bid appeared. Closing set for Aug 28. WFM ≈ $42.',
        step: s('Someone bought WFM $45 calls on the bidding-war story. Outcome?', [['zero', 'They expire worthless as WFM converts at $42'], ['paid', 'They pay because Amazon is strong']], 'zero', 'Without a new bid, nothing lifts WFM past the deal price.') },
    ],
    outcome: 'WFM converted at $42. The deal repriced the whole sector by [[correlation]]; the KR [[collar]] held its floor through a second gap.',
  },
  {
    id: 'save-2024-01', ticker: 'SAVE', title: 'JetBlue–Spirit blocked', date: 'Jan 2024',
    summary: 'A judge blocked JetBlue\'s $33.50-a-share deal; SAVE fell ≈ 47% to $7.92 in one day.',
    terms: ['risk-reward', 'expected-value', 'tail-risk', 'bull-call-spread', 'position-sizing'], tags: ['merger', 'arbitrage', 'regulation'],
    checkpoints: [
      { label: 'Before the ruling', date: '2024-01-12', context: 'SAVE ≈ $15 vs. a $33.50 deal price. DOJ sued in Mar 2023; the trial ended, ruling pending. Spirit is losing money.',
        step: s('The spread is ≈ $18: the market gives the deal low odds. Best way to bet on approval?', [['cs', 'Small bull call spread'], ['stock', 'Shares in size, it doubles if approved'], ['np', 'Sell naked puts for income']], 'cs', 'A judge\'s ruling is binary. If it goes against the deal, shares and short puts lose heavily; the spread loses only its cost.') },
      { label: 'Blocked', date: '2024-01-16', context: 'Judge Young rules for the DOJ. SAVE closed $7.92 (−47%). JBLU +4.9% to $5.13. SAVE fell ≈ 20% more the next day.',
        step: s('Why did SAVE fall far below where it traded before the deal?', [['stand', 'Its standalone value shrank while the deal propped up the price'], ['panic', 'Pure panic, it will rebound to $15']], 'stand', 'In merger arb, the downside is today\'s standalone value, and that can decay during a long deal.') },
      { label: 'Deal ends', date: '2024-03-04', context: 'JetBlue and Spirit terminate the deal. JetBlue pays Spirit a $69M fee.',
        step: s('What sizes a merger-arb trade?', [['break', 'The loss if the deal breaks, not the size of the spread'], ['spread', 'The spread: a wider spread is a bargain']], 'break', 'A wide spread often means real risk. Size so that a break is a loss you can take.') },
    ],
    outcome: 'Spirit filed for Chapter 11 in Nov 2024. The ≈ 47% [[tail-risk]] made [[position-sizing]] the key decision for arbs.',
  },
  {
    id: 'unh-2025-04', ticker: 'UNH', title: 'The UnitedHealth guidance cut', date: 'Apr 2025',
    summary: 'A guidance cut sent UNH ≈ 22% lower in a day; more bad news followed within a month.',
    terms: ['earnings', 'gap', 'cash-secured-put', 'collar', 'expected-move'], tags: ['earnings', 'healthcare', 'gap'],
    checkpoints: [
      { label: 'Before earnings', date: '2025-04-16', context: 'UNH ≈ $585. Adjusted EPS guidance $29.50–30.00, reaffirmed in January. Seen as a defensive blue chip. Options price a modest move (approximate).',
        step: s('You sell a cash-secured put 10% below the price before earnings. Main risk?', [['gap', 'A gap bigger than the implied move: you buy far above market'], ['none', 'Little risk, UNH is defensive']], 'gap', 'The expected move is not a limit. A "safe" stock can still gap through your strike.') },
      { label: 'Guidance cut', date: '2025-04-17', context: 'Guidance cut to $26.00–26.50 on higher Medicare Advantage costs. UNH opened ≈ $482, closed ≈ $454 (−22%). IV jumps.',
        step: s('You still own UNH. Cheapest way to protect what is left?', [['collar', 'A collar: sell a call to fund a put'], ['put', 'Buy outright puts at peak IV'], ['avg', 'Average down on margin']], 'collar', 'After a gap, puts are expensive. Selling a call at the same high IV pays most of the cost.') },
      { label: 'CEO exit', date: '2025-05-13', context: 'CEO Andrew Witty steps down; guidance suspended. UNH ≈ $379 → ≈ $311 (−18%). May 15: report of a criminal probe, another −11% to ≈ $274.',
        step: s('Bad news came in a cluster. What does this say about "it is priced in"?', [['cluster', 'Shocks often cluster; keep hedges until the story settles'], ['bottom', 'After one big gap, the low is in']], 'cluster', 'A broken story often breaks further. A hedge is cheapest to keep, not to rebuy after the next gap.') },
    ],
    outcome: 'UNH fell from ≈ $585 to ≈ $274 in a month. The [[expected-move]] was no limit, and a [[collar]] was a cheap way to stay hedged.',
  },
  {
    id: 'dis-2022-11', ticker: 'DIS', title: 'Iger comes back', date: 'Nov 2022',
    summary: 'After a weak quarter, Disney replaced CEO Bob Chapek with Bob Iger on a Sunday night; DIS rose ≈ 6% the next day.',
    terms: ['leaps', 'covered-call', 'gap', 'roll', 'weekly'], tags: ['media', 'management', 'event'],
    checkpoints: [
      { label: 'Earnings miss', date: '2022-11-09', context: 'Weak quarter with large streaming losses. DIS ≈ $100 → ≈ $87 (−13%).',
        step: s('You expect a multi-year turnaround but want less cash at risk than shares. Which option?', [['leaps', 'A LEAPS call, more than a year out'], ['weekly', 'Weekly OTM calls'], ['sp', 'Short-dated puts sold in size']], 'leaps', 'A turnaround takes time. Long-dated calls lose little to theta each day; weeklies need the move now.') },
      { label: 'Iger is back', date: '2022-11-21', context: 'Sunday Nov 20: the board names Bob Iger CEO again. DIS ≈ $91.80 → ≈ $97.58 (+6.3%), opened above $100.',
        step: s('On Friday you sold a weekly $95 covered call. DIS opens ≈ $100. Your situation?', [['capped', 'Gains capped at $95 plus premium; roll up and out, or accept assignment'], ['loss', 'You lose money on the shares']], 'capped', 'A covered call never loses on the shares; it only gives up the gain above the strike. Rolling buys back some of that upside for a cost.') },
      { label: 'Restructuring', date: '2023-02-09', context: 'Feb 8: Iger announces ≈ 7,000 job cuts and $5.5B of cost savings; shares rose after hours. Feb 9: closed ≈ $110 (−1.3%).',
        step: s('The after-hours jump was gone by the next close. Lesson for short-dated calls on headlines?', [['fade', 'Headline pops can fade; short-dated calls lose fast when they do'], ['hold', 'After-hours moves always hold']], 'fade', 'After-hours prices are thin. Short-dated calls need the move to hold, and theta works against them each day.') },
    ],
    outcome: 'DIS went from ≈ $87 to ≈ $110 in three months on the management change. Time was the friend of [[leaps]] holders; the [[gap]] capped weekly covered calls.',
  },
  {
    id: 'nvo-2024-12', ticker: 'NVO', title: 'CagriSema misses the bar', date: 'Dec 2024',
    summary: 'CagriSema gave 22.7% weight loss vs. the ≈ 25% Novo had talked up; shares fell ≈ 20% in Copenhagen.',
    terms: ['expected-move', 'gap', 'bear-put-spread', 'profit-target', 'iv'], tags: ['biotech', 'binary', 'pharma'],
    checkpoints: [
      { label: 'Before the readout', date: '2024-12-19', context: 'NVO ADR ≈ $103.4. Executives had often said they expected ≈ 25% weight loss in REDEFINE 1. Data due before year-end.',
        step: s('You think 25% is too high a bar. Which trade keeps risk defined?', [['bps', 'Small bear put spread'], ['nc', 'Sell naked calls'], ['short', 'Short shares in size']], 'bps', 'A readout can also surprise up. The put spread risks only its cost.') },
      { label: 'The readout', date: '2024-12-20', context: '22.7% at 68 weeks (patients on treatment). Copenhagen −20%, a record drop. ADR ≈ $103.4 → ≈ $85.0 (−18%). LLY opened ≈ +7%, closed +1.3%.',
        step: s('22.7% beat every other arm in the trial, yet the stock fell. Why?', [['bar', 'The price had the 25% target built in; missing that bar moved it'], ['failed', 'The drug failed the trial']], 'bar', 'Prices react to the result versus expectations. A good number below a public target is a miss.') },
      { label: 'Second trial', date: '2025-03-10', context: 'REDEFINE 2 (type 2 diabetes): 15.7% weight loss, below hopes. ADR ≈ $87 → ≈ $79 (−9%).',
        step: s('Your December put spread is near its max value with months to go. Next?', [['close', 'Close it or take most of the gain: little upside left'], ['hold', 'Hold to expiry for the last few cents']], 'close', 'Near max value, the spread can gain little more but can lose a lot on a rebound. Take the profit target.') },
    ],
    outcome: 'The [[gap]] came from missing a bar Novo set itself. A [[bear-put-spread]] defined the risk; a [[profit-target]] locked in the gain.',
  },
  {
    id: 'avgo-2024-12', ticker: 'AVGO', title: 'Broadcom\'s AI surge', date: 'Dec 2024',
    summary: 'AI revenue of $12.2B (+220%) and a $60–90B AI market estimate sent AVGO up ≈ 24% and past a $1T value.',
    terms: ['earnings', 'covered-call', 'iv-crush', 'roll', 'correlation'], tags: ['earnings', 'ai', 'semis'],
    checkpoints: [
      { label: 'Before earnings', date: '2024-12-12', context: 'AVGO ≈ $180.66 (after the Jul 2024 10:1 split). Results after the close. Pre-earnings IV elevated.',
        step: s('You own AVGO and want to sell the rich IV but keep upside on a big beat. Which call?', [['far', 'A far OTM covered call, or skip it this time'], ['atm', 'An ATM covered call for the most premium']], 'far', 'An ATM call gives away any gap up. A far strike keeps most of the upside and still sells some IV.') },
      { label: 'AI surge', date: '2024-12-13', context: 'FY24 AI revenue $12.2B (+220%). Three hyperscale customers: $60–90B AI market by FY2027. AVGO closed ≈ $224.80 (+24%), best day on record. Dec 16: +11% to ≈ $250.',
        step: s('Your pre-earnings calls tripled, but IV has dropped. Next step?', [['part', 'Take part off; roll the rest up to lock in gains'], ['all', 'Hold all, AI only goes up']], 'part', 'IV crush and theta now work against the calls. Rolling up takes cash off the table and keeps some upside.') },
      { label: 'DeepSeek shock', date: '2025-01-27', context: 'A low-cost Chinese AI model raises doubts about AI spending. AVGO ≈ $245 → ≈ $202 (−17%). Most AI chip stocks fell together.',
        step: s('You hold several AI chip stocks. What does this day show?', [['corr', 'They share one driver; hedge the theme, e.g. with sector puts'], ['div', 'Several names spread the risk well']], 'corr', 'High correlation means many names act as one position. A sector hedge covers the shared risk.') },
    ],
    outcome: 'A record earnings [[gap]] up, then a −17% theme shock six weeks later. [[correlation]] across AI names made the theme the real position.',
  },
  {
    id: 'x-2023-12', ticker: 'X', title: 'Nippon Steel bids for U.S. Steel', date: 'Dec 2023',
    summary: 'A $55 cash bid (40% premium) lifted X about a quarter, but politics kept a wide spread for 18 months.',
    terms: ['risk-reward', 'tail-risk', 'collar', 'expected-value', 'position-sizing'], tags: ['merger', 'arbitrage', 'politics'],
    checkpoints: [
      { label: 'Deal day', date: '2023-12-18', context: '$55 cash, 40% premium to the Dec 15 close (≈ $39). Within hours, senators from both parties oppose the deal. X jumps about a quarter, into the high $40s.',
        step: s('The spread is ≈ 12% on an all-cash deal. Why so wide?', [['pol', 'The market prices political and security-review risk'], ['cash', 'Nippon cannot pay']], 'pol', 'Financing was not the issue. The spread is the price of a political veto.') },
      { label: 'Biden blocks', date: '2025-01-03', context: 'President Biden blocks the deal on national-security grounds. X fell ≈ 6% and traded in the mid-$30s that month. The companies sue.',
        step: s('An arb who bought in the high $40s is deep in loss. What would have defined the risk at entry?', [['put', 'A put or a collar under the shares'], ['avg', 'A plan to average down on each drop']], 'put', 'A political veto is a binary event. A put caps the break loss; averaging down only adds to it.') },
      { label: 'Golden share', date: '2025-06-18', context: 'After President Trump approved a revised deal with a US "golden share", the deal closed at $55.',
        step: s('The deal paid $55 in the end. Was a large arb position right?', [['process', 'Judge by risk taken: an 18-month binary needed small size'], ['result', 'Yes, it paid, so the size was right']], 'process', 'A good result does not prove a good bet. The same trade could have ended near $35.') },
    ],
    outcome: 'Arbs who held on earned $55, but sat through a political veto. [[position-sizing]] and defined risk made the wait survivable.',
  },
  {
    id: 'smci-2024-03', ticker: 'SMCI', title: 'Super Micro joins the S&P 500', date: 'Mar 2024',
    summary: 'Index inclusion news lifted SMCI ≈ 19% in a day; it peaked at ≈ $1,229 and was back near $900 the day after inclusion.',
    terms: ['bear-call-spread', 'naked-call', 'collar', 'trend', 'iv'], tags: ['index', 'ai', 'momentum'],
    checkpoints: [
      { label: 'Inclusion news', date: '2024-03-04', context: 'Announced after the Mar 1 close: SMCI joins the S&P 500 before the open on Mar 18. ≈ $905 → ≈ $1,074 (+19%). Up from ≈ $285 at the start of 2024. Prices as traded (10:1 split in Oct 2024). IV very high.',
        step: s('You think SMCI is overheated. How do you express it?', [['bcs', 'Small bear call spread, or wait'], ['nc', 'Naked short calls at this IV'], ['short', 'Short shares before index funds buy']], 'bcs', 'Index funds are forced buyers until Mar 18. Never sell unlimited upside into forced demand.') },
      { label: 'The peak', date: '2024-03-08', context: 'Intraday high ≈ $1,229, closed ≈ $1,140 (−1.7%): a ≈ 11% intraday swing.',
        step: s('You own SMCI from $800 and want to protect the gain cheaply. Best move?', [['collar', 'A collar: sell a call to pay for a put'], ['none', 'Do nothing, index buying will carry it']], 'collar', 'With IV this high, the call you sell pays for most of the put and locks in a floor.') },
      { label: 'Inclusion day', date: '2024-03-18', context: 'First day in the index: closed ≈ $1,001 (−6.4%). Mar 19: ≈ $911 (−9%).',
        step: s('Why do new index members often fall after the effective date?', [['done', 'The forced buying is done; the known buyer is gone'], ['sell', 'Index funds must sell on day one']], 'done', 'The demand was known and dated. Once filled, price depends on normal buyers again.') },
    ],
    outcome: 'Like TSLA in 2020, a forced-buyer [[trend]] into the date, then a sell-the-news drop. [[naked-call]] sellers faced the squeeze; a [[collar]] protected holders.',
  },
]
