import type { Moment } from '../shared/types'
import { s } from './helpers'

// Market moments, batch 6. Prices and IV figures are approximate, reconstructed for teaching (as traded at the time).
// USO prices before Apr 2020 are as traded, before its 1:8 reverse split. UNG 2022 prices are as traded, before its 1:4 reverse split of Jan 2024.
// XLE 2022 prices are as traded, before its 2:1 split of Dec 2025.
export const MOMENTS_B6: Moment[] = [
  {
    id: 'uso-2014-06', ticker: 'USO', title: 'The great oil slide', date: 'Jun 2014–Jan 2015',
    summary: 'WTI fell from ≈ $107 to ≈ $44 in seven months; OPEC chose not to cut and USO lost ≈ 58%.',
    terms: ['contango', 'trend', 'iv', 'bear-put-spread', 'roll'], tags: ['commodities', 'oil', 'trend'],
    checkpoints: [
      { label: 'Summer peak', date: '2014-06-20', context: 'WTI ≈ $107, USO ≈ $39.3 (pre-2020-split price). Oil volatility index (OVX) ≈ 19. US shale output rising fast.',
        step: s('You expect oversupply to push oil lower over months. Which trade fits the view?', [['bps', 'Bear put spread a few months out, small size'], ['short', 'Short USO with no stop'], ['weekly', 'Buy weekly OTM puts every week']], 'bps', 'A slow supply story needs time. A defined-risk spread with months left gives the trend room; weekly puts lose to theta.') },
      { label: 'OPEC holds', date: '2014-11-28', context: 'On Thanksgiving OPEC chose not to cut output. WTI −10% to ≈ $66. USO ≈ $25.6 (−35% from June). OVX ≈ 36.',
        step: s('Your puts are deep ITM and IV has doubled. Best next step?', [['roll', 'Take profit on part; roll the rest to lower strikes'], ['add', 'Double the size at this IV'], ['hold', 'Hold everything to expiry, no plan']], 'roll', 'The trend is intact, but the gain is large and IV is rich. Banking part and rolling down keeps exposure with less at risk.') },
      { label: 'Contango bites', date: '2015-01-28', context: 'WTI ≈ $44, USO ≈ $16.6. The futures curve in steep contango: later months well above the front month. OVX ≈ 55.',
        step: s('A friend wants to buy USO shares to hold for the oil rebound. What is the hidden cost?', [['roll', 'Contango roll cost: USO sells cheap and buys dear every month'], ['none', 'None, USO tracks spot oil exactly']], 'roll', 'In steep contango, each monthly roll loses value. USO can lag spot oil badly even if oil recovers.') },
    ],
    outcome: 'A slow supply-driven [[trend]]: months-long puts worked. After the fall, [[contango]] made holding USO a costly way to bet on a rebound.',
  },
  {
    id: 'uso-2020-03', ticker: 'USO', title: 'The oil price war', date: 'Mar 2020',
    summary: 'OPEC+ talks failed, Saudi Arabia cut prices and raised output, and oil fell ≈ 25% in a day: the worst day since 1991.',
    terms: ['gap', 'tail-risk', 'iv', 'contango', 'position-sizing', 'cash-secured-put'], tags: ['commodities', 'oil', 'crash'],
    checkpoints: [
      { label: 'Talks fail', date: '2020-03-06', context: 'Russia rejected deeper OPEC+ cuts. WTI −10% to ≈ $41. USO ≈ $8.73 (pre-2020-split price). OVX ≈ 65. COVID cutting demand.',
        step: s('You sold USO cash-secured puts last week. The weekend brings big unknowns. Best move?', [['cut', 'Close or reduce before the weekend'], ['more', 'Sell more puts, IV is rich'], ['hold', 'Hold full size, oil is cheap']], 'cut', 'A failed cartel deal can gap prices over a weekend. Rich IV is pay for that gap risk, not free money.') },
      { label: 'Price war Monday', date: '2020-03-09', context: 'Saudi Arabia slashed its selling prices and planned more output. WTI −25% to ≈ $31, Brent −24%. USO ≈ $6.52 (−25%). OVX closed ≈ 116.',
        step: s('Your short puts are deep ITM after the gap. What did the gap show?', [['gap', 'A stop cannot protect a short put through a gap'], ['stop', 'A stop-loss would have closed it at the planned level']], 'gap', 'Prices jumped from Friday to Monday with no trades between. Only a long put wing would have capped the loss.') },
      { label: 'Contango deepens', date: '2020-03-18', context: 'WTI ≈ $20, lowest since 2002. USO ≈ $4.71. Storage filling; futures curve in very steep contango.',
        step: s('Oil looks cheap. Which way to bet on a rebound avoids the worst roll cost?', [['far', 'Small long calls or call spread on a later-dated contract or producers'], ['uso', 'Large USO share position held for months']], 'far', 'In very steep contango, USO pays a large roll cost each month. A defined-risk position avoids most of that drag.') },
    ],
    outcome: 'A political [[gap]] on top of a demand collapse. Short-premium sellers learned the cost of [[tail-risk]]; deep [[contango]] then punished buy-and-hold USO bulls.',
  },
  {
    id: 'gld-2013-04', ticker: 'GLD', title: 'The gold crash', date: 'Apr 2013',
    summary: 'Gold futures fell ≈ 13% in two sessions to ≈ $1,361 on Apr 15, 2013, the steepest drop in about 30 years.',
    terms: ['iv', 'vega', 'support-resistance', 'protective-put', 'stop-loss'], tags: ['commodities', 'gold', 'crash'],
    checkpoints: [
      { label: 'Cracks show', date: '2013-04-11', context: 'Gold ≈ $1,564, below its 2011 peak near $1,900. GLD ≈ $150. Gold volatility index (GVZ) ≈ 15. Talk of central bank gold sales and bank forecast cuts.',
        step: s('You hold GLD as a long-term holding. Gold IV is near lows. Cheapest protection?', [['put', 'Buy a protective put while IV is low'], ['none', 'No hedge: gold is a safe haven'], ['wait', 'Wait for a break below $1,520 support']], 'put', 'Low IV makes puts cheap. A "safe haven" can still fall fast when support breaks.') },
      { label: 'Friday break', date: '2013-04-12', context: 'Gold −4% to ≈ $1,501, below key support near $1,520. GLD ≈ $144 (−4.7%). Stop orders triggered as support broke.',
        step: s('Your stop sat just below $1,520. Why did many stops fill much lower?', [['crowd', 'Many stops at the same level fed the selling'], ['bad', 'The broker made an error']], 'crowd', 'Clustered stops below obvious support turn into market orders together. A put strike does not depend on fills.') },
      { label: 'Black Monday', date: '2013-04-15', context: 'Gold −9% to ≈ $1,361. GLD ≈ $131 (−8.8%). GVZ ≈ 15 → ≈ 34.5 in two days.',
        step: s('Your GLD puts are deep ITM and GVZ more than doubled. Next?', [['take', 'Sell part of the puts to lock in the vega and delta gain'], ['buy', 'Buy more puts now'], ['let', 'Let all of them expire']], 'take', 'The puts gained from both price and vega. If IV falls back, part of that gain goes away. Banking some keeps it.') },
    ],
    outcome: 'Gold fell ≈ 25% from April to late June. A [[protective-put]] bought at low [[iv]] beat a [[stop-loss]] that filled in the stampede.',
  },
  {
    id: 'slv-2011-05', ticker: 'SLV', title: 'Silver margin squeeze', date: 'Apr–May 2011',
    summary: 'Silver nearly reached $50, then five CME margin hikes in nine days helped knock SLV ≈ 29% lower in a week.',
    terms: ['margin', 'leverage', 'iv', 'trend', 'collar'], tags: ['commodities', 'silver', 'crash'],
    checkpoints: [
      { label: 'Parabolic top', date: '2011-04-28', context: 'Silver futures ≈ $49.5 intraday, near the 1980 record. SLV closed ≈ $47.3 (high ≈ $48.4). CME began raising silver margins on Apr 25.',
        step: s('You hold SLV with a large gain after a vertical rally. Best way to protect it?', [['collar', 'Collar: sell an OTM call to help pay for a put'], ['more', 'Add more on margin'], ['none', 'Do nothing, the trend is strong']], 'collar', 'Call IV is high after a parabolic run. Selling a call funds the put and locks in a price range.') },
      { label: 'Margin hikes', date: '2011-05-02', context: 'Silver fell sharply in thin Sunday-night trading. SLV ≈ $42.8 (−8.6%). More CME margin hikes announced.',
        step: s('Why do exchange margin hikes push leveraged prices down?', [['force', 'Traders without spare cash must sell to meet the higher margin'], ['value', 'They change silver\'s fair value']], 'force', 'A margin hike is a forced deleverage. Selling feeds on itself when many longs use high leverage.') },
      { label: 'The washout', date: '2011-05-05', context: 'SLV ≈ $33.7 (−11.9% that day, ≈ −29% from Apr 28). Margin up ≈ 84% across the hikes. IV very high.',
        step: s('You want to buy the dip. IV is very high. Which structure fits?', [['bps', 'Bull put spread or call spread: small, defined risk'], ['call', 'Buy ATM calls at any price'], ['margin', 'Buy SLV on full margin']], 'bps', 'High IV favors selling some premium. A defined-risk spread limits loss if the fall goes on.') },
    ],
    outcome: 'A [[leverage]] unwind forced by [[margin]] hikes. A [[collar]] at the top kept gains; buying on margin turned a dip into a wipe-out.',
  },
  {
    id: 'ung-2022-08', ticker: 'UNG', title: 'Natural gas hits $10', date: 'Aug–Sep 2022',
    summary: 'US natural gas topped $10 for the first time since 2008 on Aug 23, then fell ≈ 30% in five weeks.',
    terms: ['iv', 'skew', 'contango', 'credit-spread', 'expected-value'], tags: ['commodities', 'natgas', 'volatility'],
    checkpoints: [
      { label: '$10 gas', date: '2022-08-23', context: 'Front-month gas ≈ $10 intraday, first time since 2008. UNG ≈ $33.8 (pre-2024-split price). Low storage, Europe energy crisis, Nord Stream outage planned.',
        step: s('Call IV is extreme and calls trade above puts (call skew). You think the spike is stretched. Which trade?', [['bcs', 'Small bear call spread above the market'], ['nc', 'Sell naked calls for the huge premium'], ['puts', 'Buy many cheap OTM puts']], 'bcs', 'High call IV pays a seller, but natgas can still jump. Owning the higher call caps the loss.') },
      { label: 'Fading', date: '2022-09-07', context: 'Gas ≈ $7.8. UNG ≈ $27 (−20% from Aug 22 close). Storage builds better than feared; US LNG export plant restart delayed.',
        step: s('Your call spread is worth a small part of its credit, with weeks left. Next?', [['close', 'Close it and bank most of the gain'], ['hold', 'Hold to expiry for the last bit']], 'close', 'Little reward is left, but a new spike can still hurt. Taking profit early improves the risk-reward.') },
      { label: 'Month end', date: '2022-09-30', context: 'Gas ≈ $6.8. UNG ≈ $23.4 (−31% from Aug 22).',
        step: s('Why is UNG a poor long-term hold even after a fall like this?', [['roll', 'Contango roll cost usually eats returns over time'], ['fee', 'Only its management fee matters']], 'roll', 'Natgas futures are often in contango. UNG has needed several reverse splits for this reason.') },
    ],
    outcome: 'Extreme call [[skew]] paid defined-risk sellers. Over time, [[contango]] makes UNG a leaky way to own gas.',
  },
  {
    id: 'tlt-2022-01', ticker: 'TLT', title: 'The great bond rout', date: '2022',
    summary: 'The Fed hiked from near zero; the 10-year yield rose from ≈ 1.5% to ≈ 4.2% and TLT fell ≈ 37% to its October low.',
    terms: ['risk-free-rate', 'rho', 'trend', 'fomc', 'covered-call', 'leaps'], tags: ['rates', 'bonds', 'macro'],
    checkpoints: [
      { label: 'New year', date: '2021-12-31', context: 'TLT ≈ $148. 10-year yield ≈ 1.5%. Inflation near 7%; the Fed signals rate hikes in 2022.',
        step: s('You hold TLT as a "safe" asset. Rates look set to rise. What protects you?', [['put', 'A put or put spread on TLT, or cut size'], ['safe', 'Nothing: bonds are always safe'], ['calls', 'Buy TLT calls to add']], 'put', 'Long bonds fall when yields rise. "Safe" from default is not safe from rate risk.') },
      { label: 'Big hike', date: '2022-06-14', context: 'TLT ≈ $109 (−27% YTD). 10-year ≈ 3.5%. Hot CPI; the Fed hikes 75 bp the next day, the biggest since 1994.',
        step: s('Higher rates also change option prices. All else equal, what does a higher risk-free rate do?', [['calls', 'Raises call value and lowers put value'], ['none', 'Nothing, rates do not affect options']], 'calls', 'That is rho. The effect is small on short options but larger on LEAPS.') },
      { label: 'October low', date: '2022-10-21', context: 'TLT ≈ $93 (−37% from Dec). 10-year ≈ 4.2%. Sentiment very bearish.',
        step: s('You want to own TLT at these yields but fear more downside. Which is a measured entry?', [['csp', 'Sell a cash-secured put below the market, sized for assignment'], ['lev', 'Buy deep OTM calls with all your bond money'], ['all', 'Buy full size today']], 'csp', 'The put pays you while you wait. If assigned, you own TLT at a lower cost, at a size you planned.') },
    ],
    outcome: 'A rare [[trend]] in rates. Rising [[risk-free-rate]] hit long bonds hardest; TLT ended 2022 near $100 and fell again in 2023.',
  },
  {
    id: 'tur-2018-08', ticker: 'TUR', title: 'The lira crash', date: 'Aug 2018',
    summary: 'A US–Turkey dispute and tariff doubling sank the lira to record lows; TUR fell ≈ 32% in two weeks.',
    terms: ['correlation', 'gap', 'liquidity', 'iv', 'protective-put'], tags: ['fx', 'emerging', 'crash'],
    checkpoints: [
      { label: 'Tension builds', date: '2018-07-31', context: 'TUR ≈ $28.2. Lira ≈ 4.9 per $. Inflation ≈ 16%. US sanctions two Turkish ministers on Aug 1.',
        step: s('You hold TUR. Your loss comes from stocks and the lira at once. What matters most?', [['corr', 'Both drop together in a crisis: hedge or cut size'], ['div', 'Stocks and currency offset each other']], 'corr', 'For a US investor, falling Turkish stocks and a falling lira compound. In a crisis the two move together.') },
      { label: 'Tariff Friday', date: '2018-08-10', context: 'US doubles steel and aluminium tariffs on Turkey. Lira hits ≈ 6.8 per $ intraday. TUR ≈ $21.4 (−14.5%).',
        step: s('TUR options are thinly traded and spreads are wide. How do you enter a hedge?', [['limit', 'Limit order near mid, or use a liquid proxy'], ['market', 'Market order, speed matters most']], 'limit', 'In a thin market a market order can fill far from fair value. Limit orders keep control.') },
      { label: 'Record low', date: '2018-08-13', context: 'Lira above 7 per $ in Asia trading. TUR ≈ $19.1 (≈ −32% from Jul 31). Central bank adds liquidity steps.',
        step: s('IV in TUR options is very high now. Buy new puts?', [['no', 'Hedge cost is peak now; cut size instead, or use a put spread'], ['yes', 'Yes, buy ATM puts at any price']], 'no', 'Puts were cheap before the crisis. At peak fear, cutting size is often the cheaper hedge.') },
    ],
    outcome: 'Stock and currency risk compounded through [[correlation]]. A September rate hike to 24% steadied the lira; TUR was ≈ $22 a month later.',
  },
  {
    id: 'iwm-2024-07', ticker: 'IWM', title: 'The small-cap rotation', date: 'Jul 2024',
    summary: 'A soft CPI report lifted rate-cut hopes; IWM rose ≈ 10% in four sessions while big tech fell.',
    terms: ['cpi', 'correlation', 'iv', 'bull-call-spread', 'profit-target'], tags: ['rates', 'rotation', 'small-caps'],
    checkpoints: [
      { label: 'CPI morning', date: '2024-07-11', context: 'June CPI −0.1% m/m, 3.0% y/y. IWM ≈ $203 → ≈ $211 (+3.6%). QQQ −2.2%.',
        step: s('Small caps jump on hopes of rate cuts. How do you join with defined risk?', [['bcs', 'Bull call spread a month or two out'], ['otm', 'Many far-OTM weeklies'], ['stock', 'Buy IWM on 2x margin']], 'bcs', 'The spread defines risk and costs less than a call alone. Weeklies need a fast move every week.') },
      { label: 'Five-day run', date: '2024-07-16', context: 'IWM ≈ $225 (+10% in four sessions). A sharp rotation from big tech into small caps.',
        step: s('Your spread is near max value already. What does a profit target do here?', [['take', 'Take most of the gain now; little upside is left'], ['hold', 'Hold to expiry for the last few cents']], 'take', 'Near max value, the spread has little left to gain and much to lose. A target removes the doubt.') },
      { label: 'Round trip', date: '2024-08-05', context: 'Weak jobs data and the yen carry unwind. IWM ≈ $202, back below the CPI-day close.',
        step: s('What did the round trip teach?', [['rot', 'Sharp rotations can reverse fast; plan exits in advance'], ['trend', 'Rotations always become long trends']], 'rot', 'A crowded rotation can unwind in days. A preset exit kept the gain.') },
    ],
    outcome: 'A [[cpi]]-driven rotation that flipped normal [[correlation]] between small caps and tech. Traders with a [[profit-target]] kept the gain.',
  },
  {
    id: 'smh-2024-07', ticker: 'SMH', title: 'The chip sell-off', date: 'Jul 2024',
    summary: 'Reports of tighter China chip curbs and Taiwan remarks hit chip stocks; SMH fell ≈ 7% in a day and ≈ 24% in four weeks.',
    terms: ['correlation', 'beta-weighting', 'collar', 'iv', 'hedging'], tags: ['sectors', 'semis', 'crash'],
    checkpoints: [
      { label: 'Record high', date: '2024-07-10', context: 'SMH ≈ $281, a record close. NVDA ≈ $135. Chip stocks led the year; IV moderate.',
        step: s('You hold NVDA, AMD and TSM. One hedge for all three?', [['smh', 'SMH puts, sized by beta-weighted delta'], ['each', 'Separate puts on each stock, no sizing plan'], ['none', 'No hedge: AI demand is strong']], 'smh', 'The stocks are highly correlated. One liquid sector hedge, sized by beta, is cheaper and simpler.') },
      { label: 'Policy shock', date: '2024-07-17', context: 'Report of tougher US curbs on chip-gear sales to China; Taiwan defense remarks. SMH ≈ $254 (−7.1%). ASML −12.7%, NVDA −6.6%.',
        step: s('Your SMH puts made money. Their IV rose. What is a sensible next step?', [['part', 'Take profit on part; keep some protection'], ['all', 'Close all hedges, the shock is over']], 'part', 'Policy stories rarely end in one day. Keeping part of the hedge covers a second wave.') },
      { label: 'Carry unwind', date: '2024-08-05', context: 'SMH closed ≈ $213 after an intraday low ≈ $200 (≈ −24% from Jul 10). VIX spiked above 60 intraday.',
        step: s('You want to keep the stocks but cut cost of future protection. Which structure?', [['collar', 'Collar: sell OTM calls to fund puts'], ['nak', 'Sell naked puts to raise cash']], 'collar', 'A collar lowers hedge cost. Naked puts add downside risk, the opposite of a hedge.') },
    ],
    outcome: 'Chip stocks fell together through high [[correlation]]. A [[beta-weighting]] sector hedge covered the whole basket.',
  },
  {
    id: 'uup-2022-09', ticker: 'UUP', title: 'King dollar peaks', date: 'Sep 2022',
    summary: 'Fed hikes and a UK gilt crisis pushed the dollar index to ≈ 114.8, a 20-year high, before it fell ≈ 11% by February.',
    terms: ['trend', 'iv', 'fomc', 'risk-reversal', 'support-resistance'], tags: ['fx', 'dollar', 'macro'],
    checkpoints: [
      { label: 'Third 75 bp', date: '2022-09-21', context: 'Fed hikes 75 bp, the third in a row. Dollar index (DXY) ≈ 111. UUP ≈ $29.8. Strong upward trend all year.',
        step: s('The dollar trend is strong. You want to bet on a top. Best approach?', [['wait', 'Wait for a sign of a turn; size small if you act'], ['big', 'Big short now: it must revert'], ['naked', 'Sell naked UUP calls']], 'wait', 'Fighting a strong trend early is costly. Mean reversion needs a trigger, and size controls the cost of being early.') },
      { label: 'Gilt panic', date: '2022-09-27', context: 'UK mini-budget sent the pound to a record low ≈ 1.03 on Sep 26. DXY ≈ 114 (peak ≈ 114.8 intraday Sep 28). UUP ≈ $30.7.',
        step: s('On Sep 28 the Bank of England starts buying gilts and the dollar drops. Which trade expresses an early turn with defined risk?', [['puts', 'Small UUP put spread a few months out'], ['short', 'Short UUP with no stop'], ['calls', 'Buy more UUP calls']], 'puts', 'A central bank action can be the trigger. A put spread bets on the turn with a known max loss.') },
      { label: 'Turn confirmed', date: '2022-11-10', context: 'October CPI cooler than expected. DXY −2% in a day to ≈ 108. UUP ≈ $29.1.',
        step: s('Your put spread is in profit. The new downtrend has just started. Next?', [['roll', 'Take part off; roll the rest further out in time'], ['close', 'Close all, the move is surely over']], 'roll', 'A new trend often runs for months. Rolling out keeps exposure while banking part of the gain.') },
    ],
    outcome: 'A 20-year [[trend]] peaked after a policy shock. UUP fell to ≈ $27.3 by Feb 1, 2023; patient, defined-risk bets on the turn paid off.',
  },
  {
    id: 'xle-2022-03', ticker: 'XLE', title: 'Oil spikes on the invasion', date: 'Mar 2022',
    summary: 'After Russia invaded Ukraine, Brent hit ≈ $139 intraday on Mar 7, its highest since 2008, then fell ≈ 30% in a week.',
    terms: ['iv', 'iv-crush', 'backwardation', 'covered-call', 'trend'], tags: ['commodities', 'energy', 'geopolitics'],
    checkpoints: [
      { label: 'Invasion day', date: '2022-02-24', context: 'Russia invades Ukraine. Brent ≈ $97 the day before, spikes above $100. XLE ≈ $67 (pre-2025-split price). Oil curve in backwardation.',
        step: s('You expect oil to stay high, but energy IV jumped. How do you buy upside?', [['bcs', 'Bull call spread: the short call offsets the high IV'], ['call', 'Large ATM calls at any IV']], 'bcs', 'When IV is high, selling a higher call recovers part of the expensive premium.') },
      { label: '$139 Brent', date: '2022-03-07', context: 'Talk of a US ban on Russian oil. Brent ≈ $139 intraday, highest since 2008, closed ≈ $123. XLE ≈ $76.',
        step: s('You own XLE shares with a good gain. Call IV is very high. Which adds income at good odds?', [['cc', 'Sell OTM covered calls'], ['add', 'Add more shares at the high'], ['none', 'Do nothing']], 'cc', 'Rich call premium pays you to cap some upside after a spike. You still own the shares.') },
      { label: 'Spike fades', date: '2022-03-16', context: 'Brent ≈ $98 (−30% from the high). XLE ≈ $71.5. Energy IV falling.',
        step: s('Why did call buyers at the top lose even though XLE stayed above February levels?', [['crush', 'IV crush plus a falling price cut the call value'], ['div', 'Dividends hurt the calls']], 'crush', 'They paid peak IV. When fear fades, vega losses add to price losses.') },
    ],
    outcome: 'Spike and fade in a week, but the energy [[trend]] went on: XLE reached ≈ $92 in June. Buyers at peak [[iv]] suffered [[iv-crush]]; covered-call sellers got paid.',
  },
  {
    id: 'arkk-2021-02', ticker: 'ARKK', title: 'The innovation bubble pops', date: 'Feb 2021–Dec 2022',
    summary: 'ARKK peaked at ≈ $157 in Feb 2021 as rates rose, lost ≈ 30% in three weeks and ≈ 81% by the end of 2022.',
    terms: ['risk-free-rate', 'trend', 'moving-average', 'stop-loss', 'position-sizing'], tags: ['sectors', 'growth', 'bubble'],
    checkpoints: [
      { label: 'The peak', date: '2021-02-12', context: 'ARKK ≈ $157 record close (≈ +350% from Mar 2020). 10-year yield ≈ 1.2% and rising. Heavy retail inflows.',
        step: s('You own ARKK. Long-duration growth stocks are sensitive to rising rates. Best risk step?', [['trim', 'Trim size or add a collar'], ['margin', 'Add on margin, the trend is strong'], ['ignore', 'Ignore rates, innovation wins']], 'trim', 'Profits far in the future lose more value when rates rise. Size the position for that risk.') },
      { label: 'Rates bite', date: '2021-03-08', context: 'ARKK ≈ $110 (−30% in three weeks). 10-year ≈ 1.6%. Below its 50-day moving average.',
        step: s('Is this a dip to buy or the start of a downtrend?', [['plan', 'Unknown: use a defined-risk call spread at small size, or wait'], ['all', 'All in, it is 30% off']], 'plan', 'A 30% drop is not a price floor. Defined risk and small size let you act without betting the account.') },
      { label: 'Long bleed', date: '2022-05-11', context: 'ARKK ≈ $37 (−76% from peak). The Fed is hiking fast.',
        step: s('What was the main lesson from the long fall?', [['trend', 'A broken trend plus rising rates can last years; respect stops and size'], ['avg', 'Averaging down always wins in the end']], 'trend', 'ARKK kept falling to ≈ $30 by Dec 2022. Averaging down without a plan multiplied losses.') },
    ],
    outcome: 'A rising [[risk-free-rate]] popped a bubble in long-duration growth. [[position-sizing]] and a respected [[stop-loss]] mattered more than conviction.',
  },
  {
    id: 'lqd-2020-03', ticker: 'LQD', title: 'The Fed backstops credit', date: 'Mar 2020',
    summary: 'Corporate bond ETFs crashed below their asset value until the Fed said on Mar 23 it would buy bonds and bond ETFs; LQD rose 7% that day.',
    terms: ['liquidity', 'tail-risk', 'iv', 'credit-spread', 'bull-put-spread'], tags: ['rates', 'credit', 'macro'],
    checkpoints: [
      { label: 'Credit freeze', date: '2020-03-19', context: 'LQD ≈ $105 (−22% from Mar 6 ≈ $134). HYG ≈ $71. ETFs trade well below their asset value as bond trading dries up.',
        step: s('Why did a "safe" investment-grade ETF fall 22% in two weeks?', [['liq', 'Bond liquidity vanished; sellers hit the ETF instead'], ['default', 'Most of its bonds defaulted']], 'liq', 'Liquidity risk, not default. The ETF was the easiest thing to sell in a frozen market.') },
      { label: 'Fed steps in', date: '2020-03-23', context: 'Fed announces corporate credit facilities that will buy bonds and bond ETFs. LQD ≈ $115 (+7.4%). HYG ≈ $68.6, its low close.',
        step: s('IV is very high and a policy backstop is in place. Which defined-risk way to bet on recovery?', [['bps', 'Sell a bull put spread below the market'], ['call', 'Buy far-OTM calls at peak IV'], ['naked', 'Sell naked puts at large size']], 'bps', 'High IV pays premium sellers. A put spread caps the loss if the backstop fails.') },
      { label: 'High yield added', date: '2020-04-09', context: 'Fed widens the program to some high-yield bonds and HY ETFs. HYG +6.5% to ≈ $82. LQD ≈ $132, near its pre-crash level.',
        step: s('Your spread is near max profit with weeks left. Next?', [['close', 'Close it and lock in the gain'], ['hold', 'Hold to expiry for the last cents']], 'close', 'Little reward is left and the risk is the same. Taking it early frees capital.') },
    ],
    outcome: 'A [[liquidity]] crash, not a default wave. "Do not fight the Fed": defined-risk sellers of rich premium won once the backstop came.',
  },
  {
    id: 'kweb-2021-07', ticker: 'KWEB', title: 'China tech crackdown', date: 'Jul 2021',
    summary: 'Beijing hit DiDi and then banned for-profit tutoring; KWEB fell ≈ 21% in three sessions and ≈ 80% from its Feb 2021 peak to Mar 2022.',
    terms: ['tail-risk', 'gap', 'iv', 'position-sizing', 'bear-put-spread'], tags: ['sectors', 'china', 'regulation'],
    checkpoints: [
      { label: 'DiDi probe', date: '2021-07-06', context: 'Days after its US IPO, DiDi is hit by a cyber probe and its app is pulled. KWEB ≈ $63 (−5.2%), already −39% from Feb ≈ $104.',
        step: s('Regulation risk is rising. You hold KWEB. Best move?', [['hedge', 'Cut size or buy a put spread'], ['add', 'Add: it is 39% off the high'], ['none', 'Do nothing: policy will soften']], 'hedge', 'Policy risk can bring sudden gaps. Hedge or reduce while the market is open and calm.') },
      { label: 'Tutoring ban', date: '2021-07-26', context: 'Rules ban for-profit tutoring in core subjects. KWEB ≈ $55 (Jul 23, −8.8%) → ≈ $50 (−9.6%), then ≈ $47.7 Jul 27.',
        step: s('Weekend rules gap the market at the open. What protects you?', [['put', 'A put held before the news'], ['stop', 'A stop-loss order']], 'put', 'A stop fills after the gap. A put pays from its strike no matter where the market opens.') },
      { label: 'Relief bounce', date: '2021-07-28', context: 'Regulators calm investors; KWEB +10% to ≈ $52.5. IV still high. KWEB later fell to ≈ $21 by Mar 2022.',
        step: s('After a +10% bounce in a policy downtrend, what does process say?', [['size', 'Treat bounces with caution; keep size small and risk defined'], ['bottom', 'The bottom is in, buy full size']], 'size', 'One relief day does not end a policy trend. The ETF lost more than half again over the next eight months.') },
    ],
    outcome: 'Policy [[tail-risk]] arrived in [[gap]]s. Puts held before the news and small [[position-sizing]] beat stops and dip-buying.',
  },
]
