import type { Moment } from '../shared/types'
import { s } from './helpers'

// Market moments, batch 4: squeezes and single-stock shocks.
// Prices are as traded at the time, not adjusted for later splits (AMC 1:10 reverse 2023, TSLA 3:1 2022,
// NKLA 1:30 reverse 2024, CVNA 5:1 2026, CRWD 4:1 2026). IV and short-interest figures are approximate.
export const MOMENTS_B4: Moment[] = [
  {
    id: 'amc-2021-06', ticker: 'AMC', title: 'The popcorn squeeze', date: 'Jun 2021',
    summary: 'Retail buying drove AMC from ≈ $14 to a $72.62 intraday high in about a week, and the company sold new shares into the spike.',
    terms: ['short-interest', 'iv', 'breakeven', 'bull-call-spread', 'gamma-squeeze'], tags: ['squeeze', 'retail', 'dilution'],
    checkpoints: [
      { label: 'Week-long run', date: '2021-06-01', context: 'AMC ≈ $13.68 (May 24) → ≈ $32.04 (Jun 1). Short interest ≈ 18–20% of float. AMC sold 8.5M new shares to a hedge fund, which resold them. Call IV in the hundreds of %.',
        step: s('You expect more upside, but calls are priced at extreme IV. Which trade keeps cost and risk defined?', [['bcs', 'Small bull call spread'], ['otm', 'Many cheap far-OTM weekly calls'], ['margin', 'Shares on full margin']], 'bcs', 'The short call of the spread is also priced at high IV, so it pays back part of the cost. The loss is capped at the debit.') },
      { label: 'Record day', date: '2021-06-02', context: 'Intraday high $72.62 (+127%). Closed ≈ $62.55 (+95%). Short-dated call IV far above 300% (approximate).',
        step: s('A friend wants to buy an ATM weekly call now. What must happen for it to profit?', [['big', 'A further very large move before expiry'], ['flat', 'The stock only needs to stay flat']], 'big', 'At this IV the premium is a large part of the share price. The breakeven sits far above spot, and time decay is fast.') },
      { label: 'Share sale', date: '2021-06-03', context: 'AMC sold 11.55M shares at the market for ≈ $587M (avg ≈ $50.85). Range $37.66–$68.80. Closed ≈ $51.34 (−18%).',
        step: s('What does a company selling new shares into a squeeze do?', [['supply', 'Adds supply that can meet buyers and cap the rally'], ['bull', 'Shows the squeeze must go higher'], ['none', 'Has no effect on the price']], 'supply', 'Squeezes need scarce shares. New stock gives buyers what they want and lets shorts cover more easily.') },
    ],
    outcome: 'AMC never closed above the Jun 2 high. Late buyers paid peak [[iv]]; spreads and small size limited the cost of being wrong.',
  },
  {
    id: 'bbby-2022-08', ticker: 'BBBY', title: 'The Cohen exit', date: 'Aug 2022',
    summary: 'BBBY more than tripled in August on meme buying and Ryan Cohen\'s call position, then fell ≈ 52% in two days when he sold everything.',
    terms: ['short-interest', 'gap', 'cash-secured-put', 'assignment', 'bear-put-spread', 'iv'], tags: ['meme', 'insider', 'gap'],
    checkpoints: [
      { label: 'Peak frenzy', date: '2022-08-16', context: 'BBBY up ≈ 300% in August. A filing showed Cohen\'s fund held Jan 2023 calls at $60, $75 and $80 strikes. Intraday high ≈ $28 (+70%), closed +29%. ≈ 400M shares traded.',
        step: s('An insider\'s far-OTM calls are public. Does copying them give you his edge?', [['no', 'No: you do not know his exit plan or full position'], ['yes', 'Yes: buy the same strikes now']], 'no', 'A filing shows a position at one date, not the plan. Insiders can sell at any time after the filing period.') },
      { label: 'Sale disclosed', date: '2022-08-18', context: 'Closed ≈ $18.55 (−19.6%). After the close, filings showed Cohen sold all 7.78M shares ($18.68–$29.22) and his calls on Aug 16–17. Stock indicated −40% after hours.',
        step: s('You sold naked $15 puts during the rally for rich premium. Your position at the open is…', [['itm', 'Deep ITM: the loss is far larger than the premium'], ['safe', 'Safe: the premium was very large']], 'itm', 'A short put loses dollar for dollar below the strike minus premium. A gap opens below it, and assignment means buying at $15.') },
      { label: 'Crash day', date: '2022-08-19', context: 'Closed −40.5% at ≈ $11. Put IV still very high. Company finances weak.',
        step: s('You now expect a further decline, but puts are very expensive. Best structure?', [['bps', 'Bear put spread'], ['atm', 'Large ATM put position'], ['short', 'Short the stock']], 'bps', 'Selling the lower put cuts the cost of high IV. Short stock in a meme name with high short interest risks a new squeeze.') },
    ],
    outcome: 'Bed Bath & Beyond filed for bankruptcy in April 2023. Naked short puts were caught by the [[gap]]; a [[bear-put-spread]] defined the cost of the bear view.',
  },
  {
    id: 'vw-2008-10', ticker: 'VOW', title: 'The infinity squeeze', date: 'Oct 2008',
    summary: 'Porsche revealed control of ≈ 74% of VW; with almost no free float, shorts drove the stock above €1,000 and VW briefly became the world\'s most valuable company.',
    terms: ['short-interest', 'tail-risk', 'liquidity', 'naked-call', 'bear-put-spread'], tags: ['squeeze', 'europe', 'float'],
    checkpoints: [
      { label: 'Before the news', date: '2008-10-24', context: 'VW closed ≈ €210.85. Short interest ≈ 12–13% of shares, often paired with a long Porsche hedge. Lower Saxony owned ≈ 20%.',
        step: s('You hold a large VW short as part of a "safe" pair trade. Which add-on limits your tail risk?', [['call', 'Buy OTM VW calls as a hedge'], ['add', 'Add to the short, the pair is hedged'], ['naked', 'Sell VW calls for extra income']], 'call', 'A short stock has unlimited loss. Long calls cap that loss for a known premium. A pair hedge fails if one leg is squeezed.') },
      { label: 'Porsche reveals', date: '2008-10-27', context: 'Sunday: Porsche disclosed 42.6% plus options on 31.5% = 74.1%. Free float ≈ 6%, smaller than the short interest. VW closed ≈ €520 (+147%).',
        step: s('You are still short with no hedge. Shares to cover are scarce. Best action?', [['cover', 'Cover or hedge now; the loss has no cap'], ['wait', 'Wait: the price is irrational and must fall']], 'cover', 'When float is smaller than short interest, shorts must bid against each other. Irrational prices can go much further.') },
      { label: 'Over €1,000', date: '2008-10-28', context: 'Intraday high €1,005. Closed ≈ €945. VW briefly the most valuable listed company.',
        step: s('You expect a collapse, but put IV is extreme. Best way to bet on it?', [['bps', 'Small bear put spread'], ['short', 'Short the stock now'], ['atm', 'Buy ATM puts with a large size']], 'bps', 'The spread cuts the cost of extreme IV. Shorting into a float squeeze can still lose without limit.') },
    ],
    outcome: 'Porsche released ≈ 5% to the market on Oct 29; VW closed ≈ €517 and fell more than 58% in four days. Short stock with no hedge carried true [[tail-risk]].',
  },
  {
    id: 'tsla-2020-08', ticker: 'TSLA', title: 'The split and the whale', date: 'Aug–Sep 2020',
    summary: 'A 5-for-1 split and huge call buying, later tied to SoftBank, pushed TSLA up ≈ 80% in three weeks; then it had its worst day ever.',
    terms: ['gamma-squeeze', 'delta', 'open-interest', 'bull-call-spread', 'iv'], tags: ['split', 'flows', 'ev'],
    checkpoints: [
      { label: 'Split news', date: '2020-08-12', context: 'TSLA announced a 5-for-1 split after the Aug 11 close (≈ $1,374). Aug 12 closed ≈ $1,555 (+13%). Prices as traded in 2020, before the 2022 3:1 split.',
        step: s('What does a 5-for-1 split change about the company\'s value?', [['none', 'Nothing: five shares at one fifth of the price'], ['up', 'It makes the company worth more']], 'none', 'A split changes the unit size, not the value. Options are adjusted so contract value stays the same.') },
      { label: 'Split day', date: '2020-08-31', context: 'First day post-split: closed ≈ $498 (+12.6%; ≈ $2,213 pre-split on Aug 28). Record call volume in big tech; reports later named SoftBank as a buyer of billions of calls.',
        step: s('Dealers who sold all those calls hedge by doing what as the stock rises?', [['buy', 'Buying more stock, which adds to the rise'], ['sell', 'Selling stock to slow the rise']], 'buy', 'Short calls gain delta as price rises. Dealers buy shares to stay hedged, which feeds the trend: a gamma squeeze.') },
      { label: 'Worst day', date: '2020-09-08', context: 'S&P 500 left TSLA out of the index (Sep 4). TSLA closed ≈ $330 (−21%), −34% from the Aug 31 close. IV still elevated.',
        step: s('You want to buy the dip. Calls still carry high IV. Best structure?', [['bcs', 'Bull call spread'], ['otm', 'Far-OTM weekly calls'], ['naked', 'Sell naked puts, large size']], 'bcs', 'The spread offsets high IV with the short call. Flow-driven moves reverse fast, so keep the loss defined.') },
    ],
    outcome: 'A flow-driven [[gamma-squeeze]] works in both directions. When call buying stopped, dealer hedges unwound and TSLA fell a third in a week.',
  },
  {
    id: 'nkla-2020-09', ticker: 'NKLA', title: 'The Hindenburg report', date: 'Sep 2020',
    summary: 'Two days after a GM deal, a short seller called Nikola "an intricate fraud"; the founder resigned and the stock lost about half its value in September.',
    terms: ['collar', 'bear-put-spread', 'profit-target', 'iv', 'gap'], tags: ['fraud', 'short-report', 'ev'],
    checkpoints: [
      { label: 'GM deal', date: '2020-09-08', context: 'GM agreed to take an 11% stake (≈ $2B). NKLA jumped ≈ 40–50%. Prices as traded in 2020, before the 2024 1:30 reverse split.',
        step: s('You hold shares with a large gain on the news. Cheap way to protect it?', [['collar', 'Collar: buy a put, pay for it with a call'], ['nothing', 'Do nothing, GM confirms the story']], 'collar', 'High IV makes the sold call pay for most of the put. You keep gains to the call strike and set a floor.') },
      { label: 'Short report', date: '2020-09-10', context: 'Hindenburg alleged an "intricate fraud". NKLA fell ≈ 10% that day and ≈ 36% within days. Put IV jumped; shares were hard to borrow.',
        step: s('You believe the report and want downside exposure. Best structure?', [['bps', 'Bear put spread'], ['short', 'Short the stock'], ['atm', 'Large ATM put position']], 'bps', 'High IV makes outright puts costly; the spread sells some of it back. Short stock has squeeze and borrow-cost risk.') },
      { label: 'Founder resigns', date: '2020-09-21', context: 'Founder Trevor Milton resigned. NKLA opened ≈ $25, down ≈ 30% at worst premarket. Your put spread is near its maximum value.',
        step: s('Your bear put spread is close to its max value with weeks left. Best action?', [['take', 'Take profit now; little gain is left'], ['hold', 'Hold to expiry for the last few cents']], 'take', 'A spread cannot pay more than its width. Holding risks a rebound for very little extra reward.') },
    ],
    outcome: 'GM dropped its equity stake in November 2020; Milton was later convicted of fraud. A [[bear-put-spread]] with a [[profit-target]] captured the move with defined risk.',
  },
  {
    id: 'lk-2020-04', ticker: 'LK', title: 'The fake coffee sales', date: 'Jan–Apr 2020',
    summary: 'Luckin Coffee admitted its COO fabricated ≈ RMB 2.2B of 2019 sales; the stock fell ≈ 75% in a day and trading was halted.',
    terms: ['protective-put', 'gap', 'stop-loss', 'liquidity', 'position-sizing'], tags: ['fraud', 'china', 'halt'],
    checkpoints: [
      { label: 'Anonymous report', date: '2020-01-31', context: 'Muddy Waters shared an anonymous report alleging inflated sales. LK fell from ≈ $36.40 to an intraday $26.75, closed ≈ $32.49. The company denied it.',
        step: s('You own LK and cannot verify the report. Prudent response?', [['hedge', 'Buy puts or cut size'], ['double', 'Buy more: the company denied it'], ['ignore', 'Ignore it, short sellers are biased']], 'hedge', 'You cannot know who is right. A put or a smaller position limits the cost of being wrong.') },
      { label: 'Admission', date: '2020-04-02', context: 'Apr 1 close ≈ $26.20. Luckin said its COO fabricated ≈ RMB 2.2B (≈ $310M) of 2019 sales. Opened ≈ $4.91, closed ≈ $6.40 (−75%).',
        step: s('You had a stop-loss at $22 and no puts. Where did it fill?', [['open', 'Near the open, around $5'], ['stop', 'At $22']], 'open', 'The stock gapped over the stop. A put pays from its strike no matter where the stock opens.') },
      { label: 'Halt', date: '2020-04-07', context: 'Nasdaq halted LK pending more information. It stayed halted for about six weeks and resumed in May below $3.',
        step: s('During a long halt, what can you do with your LK options?', [['nothing', 'Nothing: you cannot trade them until it reopens'], ['close', 'Close them at the last price']], 'nothing', 'A halt freezes stock and options. Position size is the only risk control that works when you cannot trade.') },
    ],
    outcome: 'LK was delisted from Nasdaq in mid-2020. [[protective-put]] holders had a floor; stops failed in the [[gap]], and the halt removed all [[liquidity]].',
  },
  {
    id: 'ba-2019-03', ticker: 'BA', title: 'The 737 MAX grounding', date: 'Mar 2019',
    summary: 'A second 737 MAX 8 crash in five months led to a worldwide grounding; Boeing fell ≈ 11% in three days.',
    terms: ['bull-put-spread', 'collar', 'iv', 'tail-risk', 'gap'], tags: ['aerospace', 'disaster', 'regulation'],
    checkpoints: [
      { label: 'Day after crash', date: '2019-03-11', context: 'Ethiopian Airlines 302 crashed Mar 10. Fri close ≈ $422.54. Monday intraday low ≈ $365.55 (−13%); closed ≈ $400.01 (−5.3%). Put IV jumped.',
        step: s('You want to buy the dip by selling rich put premium. Which keeps risk defined?', [['bps', 'Small bull put spread'], ['naked', 'Large naked short puts'], ['margin', 'Shares on margin']], 'bps', 'IV is high, so selling premium pays well. More bad news may follow, and the long put caps the loss.') },
      { label: 'Groundings spread', date: '2019-03-12', context: 'More countries grounded the MAX. BA closed ≈ $375.41 (−6.2%). IV still elevated.',
        step: s('You hold BA shares. Puts are expensive. Lower-cost hedge?', [['collar', 'Collar: sell an OTM call to pay for a put'], ['atm', 'Buy ATM puts at any price'], ['none', 'No hedge, Boeing is too big to fail']], 'collar', 'High IV makes the sold call worth more, so it funds most of the put. You give up some upside for a floor.') },
      { label: 'FAA grounds', date: '2019-03-13', context: 'The US grounded the MAX. BA closed ≈ $377.14, almost flat on the day.',
        step: s('Why did the US grounding barely move the stock?', [['priced', 'It was widely expected and already priced in'], ['good', 'The market saw it as good news']], 'priced', 'Most of the world had already grounded the plane. Expected news moves price less than a surprise.') },
    ],
    outcome: 'The MAX stayed grounded for about 20 months. Defined-risk dip buyers survived the second leg down; it was a slow [[tail-risk]], not a one-day [[gap]].',
  },
  {
    id: 'ba-2024-01', ticker: 'BA', title: 'The door-plug blowout', date: 'Jan 2024',
    summary: 'A door plug blew out of a new 737 MAX 9 on a Friday night; Boeing gapped ≈ 8% lower on Monday and kept sliding.',
    terms: ['gap', 'cash-secured-put', 'collar', 'leaps', 'iv'], tags: ['aerospace', 'weekend', 'regulation'],
    checkpoints: [
      { label: 'Friday night', date: '2024-01-05', context: 'BA closed ≈ $249.00. That evening a door plug blew out on Alaska Airlines 1282; all 171 passengers and 6 crew survived. Markets closed until Monday.',
        step: s('You sold BA $240 puts for income. What does the weekend mean for you?', [['gap', 'No exit until Monday; it can open far below $240'], ['safe', 'The strike protects you'], ['exit', 'You can close in after-hours options trading']], 'gap', 'Equity options trade only in regular hours. Weekend news arrives as a gap you cannot trade before.') },
      { label: 'Monday open', date: '2024-01-08', context: 'FAA grounded 171 MAX 9 jets on Jan 6. BA opened ≈ $228, closed ≈ $229 (−8%). IV up.',
        step: s('You hold BA shares and fear more news. Hedge that uses the higher IV?', [['collar', 'Collar: sell an OTM call, buy a put'], ['buy', 'Buy weekly ATM puts each week']], 'collar', 'The call sale funds most of the put. Rolling weekly puts at high IV costs a lot over time.') },
      { label: 'Production cap', date: '2024-01-24', context: 'FAA said it would not approve any MAX production increase until quality issues are fixed. BA ≈ $214, ≈ −14% since Jan 5.',
        step: s('This crisis may last months. Better expiry for a bearish or hedge position?', [['long', 'A longer expiry that covers the slow process'], ['short', 'Weeklies, they are cheaper']], 'long', 'Weeklies decay before slow regulatory news arrives. More time costs more, but matches how this risk unfolds.') },
    ],
    outcome: 'A weekend [[gap]] first, then a slow slide. Short puts could not exit before Monday; time-matched hedges fit the long crisis.',
  },
  {
    id: 'cvna-2023', ticker: 'CVNA', title: 'The comeback squeeze', date: '2023',
    summary: 'Carvana went from bankruptcy fears near $4 to ≈ $53, up ≈ 1,000% in 2023, as a debt deal squeezed a ≈ 47% short interest.',
    terms: ['short-interest', 'naked-call', 'bear-call-spread', 'leaps', 'bull-put-spread', 'roll'], tags: ['squeeze', 'debt', 'comeback'],
    checkpoints: [
      { label: 'Bankruptcy fears', date: '2023-01-03', context: 'CVNA ≈ $4.63, down ≈ 98% from its 2021 high; Dec 7 low ≈ $3.55. Heavy debt. Short interest very high. Call and put IV extreme.',
        step: s('You think CVNA goes to zero. Calls pay rich premium. Best way to sell them?', [['bcs', 'Bear call spread'], ['naked', 'Naked calls, the stock is doomed']], 'bcs', 'Heavy short interest can turn good news into a squeeze. The long call caps the loss.') },
      { label: 'Debt deal', date: '2023-07-19', context: 'A debt exchange cut debt by > $1.2B; first positive adjusted EBITDA. CVNA +40% to ≈ $55.80, > 1,000% YTD. Short interest ≈ 47% of float.',
        step: s('You hold January LEAPS calls bought near $5, now worth many times their cost. Next?', [['roll', 'Take profit on part; roll the rest up and out'], ['hold', 'Hold all; shorts must still cover']], 'roll', 'Banking part of a large gain removes the risk of giving it all back. Rolling up keeps upside with less capital at stake.') },
      { label: 'Halved again', date: '2023-11-01', context: 'CVNA ≈ $26, about half its July level. IV still high.',
        step: s('You want to own CVNA again near this level. Way to use the high IV?', [['bps', 'Bull put spread below the price'], ['margin', 'Shares on margin'], ['otm', 'Far-OTM weekly calls']], 'bps', 'Selling puts collects high IV. The long put caps the loss if the slide continues.') },
    ],
    outcome: 'CVNA ended 2023 ≈ $52.94. Shorts lost billions; naked call sellers were wiped out by a [[short-interest]] squeeze, while defined-risk bears survived.',
  },
  {
    id: 'djt-2024-03', ticker: 'DJT', title: 'The Trump Media debut', date: 'Mar–Apr 2024',
    summary: 'Trump Media listed via a SPAC merger, hit $79.38 on day one, then lost more than half its value in three weeks after a $58M loss.',
    terms: ['iv', 'bear-put-spread', 'collar', 'bear-call-spread', 'naked-call'], tags: ['spac', 'meme', 'listing'],
    checkpoints: [
      { label: 'Merger vote', date: '2024-03-22', context: 'DWAC holders approved the merger. DWAC closed ≈ $36.94. Valuation far above revenue. IV extreme.',
        step: s('You think the valuation is too high. Best way to express it?', [['bps', 'Small bear put spread'], ['short', 'Short the stock'], ['naked', 'Sell naked calls']], 'bps', 'Fan-driven stocks can spike first. Short stock and naked calls have no loss cap; the spread does.') },
      { label: 'First day', date: '2024-03-26', context: 'First trade as DJT: opened ≈ $70.90, high $79.38, closed ≈ $57.99 (+16%). Market value ≈ $8B. IV extreme.',
        step: s('You held DWAC from $37 and now have a big gain. Protect it cheaply?', [['collar', 'Collar: the rich call premium pays for a put'], ['hold', 'Hold, it can only go up']], 'collar', 'At extreme IV the call you sell is worth a lot. It funds a put and sets a floor under the gain.') },
      { label: '$58M loss', date: '2024-04-01', context: 'Filing: 2023 net loss $58.2M on revenue of $4.1M; auditors raised going-concern doubt. Closed ≈ $48.66 (−21%). IV still high.',
        step: s('You want to sell rich call premium. Which keeps risk defined?', [['bcs', 'Bear call spread above the price'], ['naked', 'Naked calls']], 'bcs', 'Meme stocks can spike on any headline. The long call caps the loss at the spread width.') },
    ],
    outcome: 'DJT closed ≈ $22.84 on Apr 16 and fell near $12 in September. Defined-risk bears survived the first-day spike that hurt [[naked-call]] sellers.',
  },
  {
    id: 'smci-2024-10', ticker: 'SMCI', title: 'The auditor walks out', date: 'Oct–Nov 2024',
    summary: 'Super Micro\'s auditor EY resigned over governance concerns; the stock fell ≈ 33% in a day and kept falling to ≈ $18.',
    terms: ['gap', 'bull-put-spread', 'bear-put-spread', 'profit-target', 'iv'], tags: ['accounting', 'gap', 'ai'],
    checkpoints: [
      { label: 'Late filing', date: '2024-10-29', context: 'SMCI ≈ $49.12 (after a 10:1 split on Oct 1). Its annual report was overdue since late August, after a short-seller report.',
        step: s('SMCI looks cheap and puts pay well. You want to sell puts. Safer form?', [['bps', 'Small bull put spread'], ['naked', 'Large naked puts'], ['margin', 'Shares on margin']], 'bps', 'An overdue filing is open event risk. A gap can skip far past a short put; the long put caps it.') },
      { label: 'EY resigns', date: '2024-10-30', context: 'EY said it could no longer rely on management\'s and the audit committee\'s statements. SMCI closed ≈ $33.07 (−33%). Put IV very high.',
        step: s('You now want downside exposure. Puts are costly. Structure?', [['bps', 'Bear put spread'], ['atm', 'Buy ATM puts, large size']], 'bps', 'The short lower put sells back some of the high IV. The cost and the loss are both defined.') },
      { label: 'Near the low', date: '2024-11-14', context: 'SMCI ≈ $18.01 after weak preliminary results. Nasdaq listing at risk. Your put spread is near its max value.',
        step: s('Your bear put spread is near max value. Next?', [['take', 'Take profit: only a little gain is left'], ['hold', 'Hold to expiry, delisting is coming']], 'take', 'A spread cannot pay more than its width. A good headline can trigger a sharp rebound.') },
    ],
    outcome: 'On Nov 18 SMCI hired BDO and filed a Nasdaq plan; it closed ≈ $28.27 (+31%) on Nov 19. A [[profit-target]] on the spread kept the gain.',
  },
  {
    id: 'mstr-2024-11', ticker: 'MSTR', title: 'The bitcoin proxy', date: 'Nov 2024',
    summary: 'MicroStrategy sold stock and bonds to buy bitcoin; MSTR more than doubled in about two weeks, then reversed 16% in a day when Citron went short.',
    terms: ['leverage', 'position-sizing', 'roll', 'iv', 'correlation'], tags: ['crypto', 'proxy', 'momentum'],
    checkpoints: [
      { label: 'Election day', date: '2024-11-05', context: 'MSTR ≈ $227.80 (after a 10:1 split in Aug 2024). Bitcoin ≈ $69K. MSTR held ≈ 252K BTC and traded well above the value of its bitcoin. IV far above most large stocks.',
        step: s('You want bitcoin exposure through MSTR calls. Key sizing point?', [['size', 'MSTR moves more than bitcoin: size smaller'], ['same', 'Size it like a bitcoin position']], 'size', 'MSTR adds debt and a premium on top of bitcoin. Its moves are larger, and its options are levered again.') },
      { label: 'Big buy', date: '2024-11-11', context: 'MSTR bought 27,200 BTC for ≈ $2.03B. Bitcoin ≈ $88K. MSTR closed ≈ $340 (+26%).',
        step: s('Calls you bought Nov 5 are worth three times their cost. Next?', [['roll', 'Take part off; roll the rest up'], ['add', 'Add more at higher strikes']], 'roll', 'Taking part of the gain locks it in. Rolling up keeps upside with less money at risk.') },
      { label: 'Citron short', date: '2024-11-21', context: 'MSTR bought 51,780 BTC (≈ $4.6B) and sold $3B of 0% convertibles. Intraday high ≈ $543; Citron said it was short; closed ≈ $397 (−16%). Bitcoin ≈ $98K, still rising.',
        step: s('Bitcoin rose but MSTR fell 16%. What does it show?', [['prem', 'The premium over its bitcoin can shrink on its own'], ['btc', 'Bitcoin must be about to fall']], 'prem', 'MSTR is bitcoin plus a premium. When the premium shrinks, MSTR falls even as bitcoin rises.') },
    ],
    outcome: 'MSTR ended 2024 ≈ $290 while bitcoin stayed near its highs. A proxy has its own risk; its [[correlation]] to bitcoin is not 1.',
  },
  {
    id: 'gme-2024-05', ticker: 'GME', title: 'Roaring Kitty returns', date: 'May–Jun 2024',
    summary: 'Keith Gill\'s first post in three years sent GME up ≈ 180% in two days; GameStop sold 120M new shares into the spikes.',
    terms: ['iv-crush', 'vega', 'theta', 'profit-target', 'iv'], tags: ['meme', 'volatility', 'dilution'],
    checkpoints: [
      { label: 'The post', date: '2024-05-13', context: 'Gill posted on X on May 12. GME ≈ $17.46 (May 10) → ≈ $30.45 (+74%) with volatility halts. Call IV in the hundreds of %.',
        step: s('You buy calls at this IV. If GME then goes flat, what happens?', [['crush', 'IV falls and the calls lose value'], ['hold', 'The calls hold their value']], 'crush', 'High IV is a large part of the premium. When excitement fades, vega losses and theta hit together.') },
      { label: 'Gap and fade', date: '2024-05-14', context: 'Opened ≈ $64.83 (the high), closed ≈ $48.75. GameStop later said it sold 45M shares in May. By May 17 GME ≈ $22.',
        step: s('Calls you bought May 10 are up many times at the open. Next?', [['take', 'Take most of the profit into the spike'], ['hold', 'Hold for a 2021-size squeeze']], 'take', 'Meme spikes fade fast, and IV drops with them. Sell into strength when the gain matches your plan.') },
      { label: 'Livestream', date: '2024-06-07', context: 'Gill showed 120,000 Jun 21 $20 calls. GME moved up earnings and filed to sell up to 75M shares. Jun 6 ≈ $46.55; Jun 7 closed ≈ $28.22 (−39%).',
        step: s('You hold Jun 21 $40 calls with two weeks left; GME ≈ $28. Best action?', [['close', 'Close or cut them now; theta speeds up'], ['hope', 'Hold and hope for another spike']], 'close', 'Short-dated OTM calls lose value fast near expiry. A plan beats hope when time is running out.') },
    ],
    outcome: 'GameStop raised ≈ $2.1B from the June sale alone. Late call buyers lost to [[iv-crush]] and [[theta]]; taking profit into spikes was the edge.',
  },
  {
    id: 'crwd-2024-07', ticker: 'CRWD', title: 'The global outage', date: 'Jul 2024',
    summary: 'A faulty CrowdStrike update crashed ≈ 8.5M Windows PCs worldwide; the stock fell ≈ 41% at its low in about two weeks.',
    terms: ['gap', 'bull-put-spread', 'adjustment', 'max-loss', 'iv'], tags: ['tech', 'outage', 'gap'],
    checkpoints: [
      { label: 'Outage day', date: '2024-07-19', context: 'A bad Falcon update crashed ≈ 8.5M Windows PCs; airlines, banks and hospitals hit. Jul 18 close ≈ $343.05. Opened ≈ $294.51, closed ≈ $304.96 (−11%).',
        step: s('You want to buy the dip right away. The damage is still unknown. Best approach?', [['wait', 'Wait, or use a small defined-risk spread'], ['calls', 'Buy many calls at the open']], 'wait', 'The first gap rarely prices all the costs and lawsuits. IV is high, so outright calls are expensive.') },
      { label: 'Second leg', date: '2024-07-22', context: 'CRWD closed ≈ $263.91 (−13.5%), −23% in two sessions. Put IV high.',
        step: s('You want to sell rich put premium near here. Which keeps risk defined?', [['bps', 'Bull put spread well below the price'], ['naked', 'Naked puts at the money']], 'bps', 'IV pays well, but more bad news can come. The long put caps the loss.') },
      { label: 'Market sell-off', date: '2024-08-05', context: 'Delta blamed the outage for heavy costs. A broad market sell-off hit too. Intraday low ≈ $200.81 (−41% from Jul 18); closed ≈ $222.05.',
        step: s('Your bull put spread is now ITM. What does your plan say?', [['plan', 'Close or roll at the planned loss'], ['wait', 'Hold, it must bounce']], 'plan', 'The spread caps the worst case, but a plan stops a bad trade from reaching it. Adjust by rule, not by hope.') },
    ],
    outcome: 'CRWD recovered to new highs by December 2024 (≈ $388). Spreads with an [[adjustment]] plan survived the 41% drawdown; size and [[max-loss]] did the work.',
  },
]
