import type { Moment } from '../shared/types'
import { s } from './helpers'

// Market moments, batch 1. Prices and IV figures are approximate, reconstructed for teaching (as traded at the time).
// Prices are as traded at the time (not adjusted for later splits: AAPL 7:1 2014 and 4:1 2020, AMZN 20:1 2022,
// NVDA 10:1 2024, NFLX 10:1 2025).
export const MOMENTS_B1: Moment[] = [
  {
    id: 'amzn-2022-02', ticker: 'AMZN', title: 'The Rivian windfall', date: 'Feb 2022',
    summary: 'A day after a sector sell-off, an $11.8B Rivian gain, a Prime price hike and strong AWS sent AMZN up 13.5%.',
    terms: ['earnings', 'gap', 'iv', 'bull-call-spread', 'roll'], tags: ['earnings', 'gap', 'tech'],
    checkpoints: [
      { label: 'Report day', date: '2022-02-03', context: 'META fell 26% this morning. AMZN closed ≈ $2,777 (−7.8%) in sympathy. Amazon reports after the close. Prices as traded before the 2022 20:1 split. IV high.',
        step: s('You are bullish on Amazon. One call costs a lot at this IV. Which structure fits?', [['bcs', 'Bull call spread, sized to lose the debit'], ['otm', 'Many far-OTM weekly calls'], ['np', 'Sell naked puts in large size']], 'bcs', 'The short call offsets part of the high IV you pay. The debit is the most you can lose.') },
      { label: 'After hours', date: '2022-02-03', context: 'Net income ≈ $14.3B, including an ≈ $11.8B pre-tax gain on the Rivian stake. Prime fee raised from $119 to $139. Stock indicated sharply higher.',
        step: s('Headline EPS was ≈ $27.75, far above estimates. How do you read it?', [['core', 'Strip out the one-off Rivian gain; judge AWS, margins, guidance'], ['eps', 'The EPS beat alone explains the move']], 'core', 'A paper gain on an investment does not repeat. Traders price the core business and the outlook.') },
      { label: 'Next day', date: '2022-02-04', context: 'Closed ≈ $3,153 (+13.5%), high ≈ $3,224. Your call spread is near its max value. IV fell after the report.',
        step: s('You still like the trend. What do you do with the spread?', [['roll', 'Close it, bank the gain, and maybe roll to higher strikes'], ['hold', 'Hold to expiry for the last few dollars']], 'roll', 'Near max value, little upside remains and a reversal can take it back. Rolling resets the risk at a new, defined size.') },
    ],
    outcome: 'A [[gap]] up one day after a sympathy drop. The [[bull-call-spread]] capped the IV cost; reading the core numbers beat reading the headline EPS.',
  },
  {
    id: 'meta-2022-10', ticker: 'META', title: 'The metaverse bill', date: 'Oct 2022',
    summary: 'Rising Reality Labs losses and a $34–39B capex plan for 2023 sent META down 24.6% in a day.',
    terms: ['cash-secured-put', 'bull-put-spread', 'assignment', 'earnings', 'gap'], tags: ['earnings', 'gap', 'mega-cap'],
    checkpoints: [
      { label: 'Before earnings', date: '2022-10-26', context: 'META ≈ $130, down ≈ 61% in 2022 (≈ $336 at the 2021 close). IV high before the report.',
        step: s('META looks "cheap". You want to sell puts for income. Safer structure?', [['bps', 'Bull put spread below the expected move'], ['csp', 'Cash-secured puts on far more shares than you want'], ['nk', 'Naked puts on margin']], 'bps', 'A long put below the short put caps the loss. A stock down 61% can still fall a lot more.') },
      { label: 'After hours', date: '2022-10-26', context: 'Reality Labs lost ≈ $3.67B in the quarter. Meta guided 2023 capex to $34–39B and said Reality Labs losses will grow significantly. Stock indicated −20% or more.',
        step: s('A friend sold cash-secured $120 puts. The stock will open far below $120. What happens at expiry?', [['assign', 'Likely assignment: buys shares at $120, worth less'], ['safe', 'Nothing, the premium covers it']], 'assign', 'An ITM short put is usually assigned. The premium only lowers the cost basis a little.') },
      { label: 'Next day', date: '2022-10-27', context: 'Opened ≈ $98, closed ≈ $97.94 (−24.6%). It fell to ≈ $88.91 by Nov 3.',
        step: s('What made the bull put spread better than the cash-secured put here?', [['cap', 'Loss was capped at the width minus credit'], ['credit', 'It collected more premium']], 'cap', 'A spread takes less premium, but the long put stops the loss. "Cheap" is not a floor.') },
    ],
    outcome: 'A cheap stock got cheaper. [[cash-secured-put]] sellers faced [[assignment]] far below the strike; the [[bull-put-spread]] defined the loss.',
  },
  {
    id: 'meta-2023-02', ticker: 'META', title: 'The year of efficiency', date: 'Feb 2023',
    summary: 'Cost cuts, a $40B buyback addition and a revenue beat sent META up 23.3% in a day.',
    terms: ['bear-call-spread', 'naked-call', 'max-loss', 'gap', 'iv-crush'], tags: ['earnings', 'gap', 'mega-cap'],
    checkpoints: [
      { label: 'Before earnings', date: '2023-02-01', context: 'META closed ≈ $153, up ≈ 72% from its Nov 3 closing low (≈ $89). Bears expect the rally to fade. IV elevated.',
        step: s('You think the bounce has gone too far. Which bearish trade keeps risk defined?', [['bcs', 'Small bear call spread'], ['nc', 'Sell naked calls into the report']], 'bcs', 'A naked call has unlimited loss on an upside gap. The spread caps it at width minus credit.') },
      { label: 'After hours', date: '2023-02-01', context: 'Revenue ≈ $32.2B, above ≈ $31.5B expected. Zuckerberg called 2023 the "year of efficiency". Buyback authorization raised by $40B. Stock indicated ≈ +19%.',
        step: s('Your $165/$175 bear call spread is now fully ITM. Your loss is…', [['cap', 'The max loss: $10 width minus the credit'], ['more', 'Larger the higher META goes']], 'cap', 'Above the long strike, every extra dollar of rally is offset. The loss stops at the planned max.') },
      { label: 'Next day', date: '2023-02-02', context: 'Opened ≈ $183, closed ≈ $188.77 (+23.3%). IV fell sharply after the report.',
        step: s('Now you turn bullish. What changed in option prices after the report?', [['cheap', 'IV crush made options cheaper; use a small, defined position'], ['same', 'Nothing, options cost the same as yesterday']], 'cheap', 'After the event, IV drops. Buying after the news avoids the pre-report premium, but the gap is already in the price.') },
    ],
    outcome: 'A short-squeeze-style [[gap]] up. The [[bear-call-spread]] lost its known [[max-loss]]; a [[naked-call]] had no ceiling.',
  },
  {
    id: 'meta-2024-02', ticker: 'META', title: 'The first dividend', date: 'Feb 2024',
    summary: 'Profit tripled, Meta started a $0.50 dividend and added $50B of buybacks; the stock rose 20.3% and added ≈ $196B in a day.',
    terms: ['covered-call', 'ex-dividend', 'early-exercise', 'dividend-risk', 'earnings'], tags: ['earnings', 'dividend', 'mega-cap'],
    checkpoints: [
      { label: 'Before earnings', date: '2024-02-01', context: 'META ≈ $395 near a record. You own 100 shares and sold a March $420 covered call for income. IV elevated.',
        step: s('What does the covered call do to your earnings risk?', [['cap', 'Caps your upside at $420 plus premium; downside barely changes'], ['hedge', 'It protects you if the stock gaps down']], 'cap', 'The premium is a small cushion. A covered call gives away the upside; it is not a hedge.') },
      { label: 'Next day', date: '2024-02-02', context: 'First dividend: $0.50 a quarter. Buyback raised by $50B. Closed ≈ $474.99 (+20.3%), a record one-day value gain at the time. Your $420 call is deep ITM.',
        step: s('Your shares gained above $420, but the short call lost about the same. Net result?', [['capped', 'Profit capped at $420 − entry + premium'], ['full', 'You keep the full +20%']], 'capped', 'Above the strike, share gains and call losses cancel. That is the trade-off you sold.') },
      { label: 'Before ex-dividend', date: '2024-02-20', context: 'META ≈ $471.75. Ex-dividend date Feb 21 (record date Feb 22). Your $420 call is ≈ $52 ITM with very little time value left.',
        step: s('What is the risk on your deep-ITM short call today?', [['early', 'Early exercise: the holder may call the shares to get the $0.50'], ['none', 'None, calls are never exercised before expiry']], 'early', 'When the dividend is larger than the call\'s extrinsic value, early exercise is rational. Expect to lose the shares and the dividend.') },
    ],
    outcome: 'A record [[gap]] up. The [[covered-call]] capped the gain, and the new dividend added [[early-exercise]] risk before the [[ex-dividend]] date.',
  },
  {
    id: 'nflx-2022-01', ticker: 'NFLX', title: 'The weak forecast', date: 'Jan 2022',
    summary: 'Netflix guided to 2.5M Q1 subscriber adds versus ≈ 6.9M expected; the stock fell 21.8%.',
    terms: ['collar', 'protective-put', 'earnings', 'gap', 'trend'], tags: ['earnings', 'gap', 'streaming'],
    checkpoints: [
      { label: 'Before earnings', date: '2022-01-20', context: 'NFLX ≈ $508, down ≈ 26% from its Nov 2021 record close (≈ $692). Prices as traded before the 2025 10:1 split. Puts are expensive.',
        step: s('You hold shares and want protection, but puts cost a lot. Which lowers the cost?', [['collar', 'Collar: buy a put, sell an OTM call to pay for it'], ['none', 'No hedge, it has already fallen 26%'], ['cc', 'Covered call only']], 'collar', 'The short call funds the put. You give up upside above the call strike in return for a floor.') },
      { label: 'After hours', date: '2022-01-20', context: 'Q4 adds ≈ 8.3M, but Q1 guidance ≈ 2.5M vs ≈ 6.9M expected. Stock indicated −20%.',
        step: s('The guide, not the quarter, moved the stock. What does that say about earnings risk?', [['guide', 'Guidance often drives the gap more than the past quarter'], ['beat', 'A beat on the quarter protects the stock']], 'guide', 'Prices look forward. A good quarter with weak guidance can still gap down.') },
      { label: 'Next day', date: '2022-01-21', context: 'Opened ≈ $400, closed ≈ $397.50 (−21.8%). It closed ≈ $366 on Jan 25. Your collar put is deep ITM.',
        step: s('The collar did its job. Lesson about the "already down 26%" argument?', [['trend', 'A falling stock can fall further; hedge before the event'], ['floor', 'A big prior drop is a reliable floor']], 'trend', 'A prior decline is not support. Only the put defined the loss through the gap.') },
    ],
    outcome: 'Guidance drove a 22% [[gap]]. The [[collar]] gave a floor at low net cost; an unhedged "it is already cheap" view did not.',
  },
  {
    id: 'snap-2021-10', ticker: 'SNAP', title: 'Apple privacy bites', date: 'Oct 2021',
    summary: 'Apple\'s tracking rules hurt ad measurement; SNAP missed on revenue and fell 26.6%, and peers fell with it.',
    terms: ['correlation', 'earnings', 'gap', 'hedging', 'long-put'], tags: ['earnings', 'gap', 'social'],
    checkpoints: [
      { label: 'Before earnings', date: '2021-10-21', context: 'SNAP ≈ $75. Apple\'s App Tracking Transparency (iOS 14.5) limits ad targeting. Snap reports today; Facebook reports Oct 25.',
        step: s('You own SNAP, FB and PINS, all ad-funded. What is the key risk tonight?', [['corr', 'One shared cause can hit all three at once'], ['single', 'Only SNAP is at risk tonight']], 'corr', 'The Apple change hits every app-ad business. Correlated holdings are one bet, not three.') },
      { label: 'After hours', date: '2021-10-21', context: 'Revenue ≈ $1.07B, ≈ $40M below estimates. Snap blamed Apple\'s privacy changes. Stock indicated ≈ −25%.',
        step: s('You want to hedge the other ad stocks before tomorrow\'s open. Most direct tool?', [['puts', 'Small long puts on the exposed names'], ['stop', 'Stop-loss orders at today\'s prices'], ['nothing', 'Nothing, it is a Snap-only problem']], 'puts', 'A gap open skips stops. Puts define the loss, but they cost more once the news is out.') },
      { label: 'Next day', date: '2021-10-22', context: 'SNAP closed ≈ $55.14 (−26.6%). FB ≈ −5.1%, PINS ≈ −5.4%.',
        step: s('What did this day teach about earnings season?', [['peer', 'A peer\'s report can move your stock before its own'], ['iso', 'Each stock only moves on its own report']], 'peer', 'Read-through from peers is real. Hedge the shared risk, not only the next date on your calendar.') },
    ],
    outcome: 'One report moved a whole sector. [[correlation]] turned three holdings into one bet; [[hedging]] with puts had to come before the open.',
  },
  {
    id: 'snap-2022-02', ticker: 'SNAP', title: 'From −24% to +59%', date: 'Feb 2022',
    summary: 'SNAP fell 23.6% in sympathy with META, then reported its first net profit and jumped 58.8% the next day.',
    terms: ['profit-target', 'iv-crush', 'short-strangle', 'correlation', 'gap'], tags: ['earnings', 'gap', 'social'],
    checkpoints: [
      { label: 'Sympathy drop', date: '2022-02-03', context: 'META −26% on its report. SNAP closed ≈ $24.50 (−23.6%). Snap reports after the close. Your SNAP puts, bought last week, are up a lot.',
        step: s('Your puts gained on META\'s news. Snap reports tonight. Next?', [['take', 'Take most of the profit before the report'], ['hold', 'Hold all of it, Snap will miss too']], 'take', 'The gain came from a peer. Snap\'s own report is a new coin flip, and IV crush hits after it.') },
      { label: 'After hours', date: '2022-02-03', context: 'First quarterly net profit (≈ $22.5M). Revenue ≈ $1.3B (+42%), daily users ≈ 319M, both above estimates. Stock indicated ≈ +50%.',
        step: s('A trader held the puts through the report. What hit them?', [['both', 'The price jump and the IV crush together'], ['theta', 'Only one day of time decay']], 'both', 'Delta and vega both turned against the puts. A profit target would have locked the gain.') },
      { label: 'Next day', date: '2022-02-04', context: 'Closed ≈ $38.91 (+58.8%) from ≈ $24.50.',
        step: s('Another trader sold a ±25% short strangle at the close. Result?', [['breach', 'The call side was far ITM: a large loss'], ['safe', 'Safe, ±25% is very wide']], 'breach', 'A 59% move broke even a wide strangle. After a 24% day, the real risk was larger than the strikes assumed.') },
    ],
    outcome: 'A [[correlation]] drop and an own-news [[gap]] in two days. A [[profit-target]] saved the put gains; a [[short-strangle]] was not wide enough.',
  },
  {
    id: 'pypl-2022-02', ticker: 'PYPL', title: 'The 750M target dropped', date: 'Feb 2022',
    summary: 'PayPal dropped its 750M-user goal and cut guidance; the stock fell 24.6%, its worst day on record.',
    terms: ['long-call', 'iv-crush', 'theta', 'earnings', 'trend'], tags: ['earnings', 'gap', 'fintech'],
    checkpoints: [
      { label: 'Before earnings', date: '2022-02-01', context: 'PYPL ≈ $176, down ≈ 43% from its Jul 2021 record close (≈ $309). Up ≈ 7% in two days. IV elevated.',
        step: s('You want calls for a rebound. When is the cost lower?', [['after', 'After the report, when IV has dropped'], ['before', 'Before the report, IV does not matter']], 'after', 'Calls bought before the event pay for the expected move. After the report, IV crush makes the same call cheaper.') },
      { label: 'After hours', date: '2022-02-01', context: 'PayPal dropped its goal of 750M active accounts by 2025, closed ≈ 4.5M illegitimate accounts and cut its outlook. Stock indicated ≈ −20%.',
        step: s('A trader bought weekly OTM calls before the report. Value now?', [['zero', 'Near zero: price fell and IV collapsed'], ['half', 'About half, the time value remains']], 'zero', 'Far-OTM weekly calls lose almost all value when the stock gaps away and IV drops.') },
      { label: 'Follow-through', date: '2022-02-03', context: 'Feb 2 closed ≈ $132.57 (−24.6%), ≈ $50B of value lost. Feb 3 ≈ $124.30 (−6.2%). IV is lower now.',
        step: s('Calls are now cheaper. Is it time to buy the dip with size?', [['wait', 'Wait, or use a small, defined position; guidance cuts often keep falling'], ['all', 'Yes, buy many calls, it is oversold']], 'wait', 'Cheap options are not a signal. A goal cut can start a downtrend; theta works against a call while it waits.') },
    ],
    outcome: 'A broken growth story. Pre-report [[long-call]] buyers lost to price and [[iv-crush]]; the post-gap [[trend]] kept going down.',
  },
  {
    id: 'nvda-2024-02', ticker: 'NVDA', title: 'The $277B day', date: 'Feb 2024',
    summary: 'Revenue of $22.1B (+265%) and a $24B guide lifted NVDA 16.4%, a record one-day value gain of ≈ $277B.',
    terms: ['straddle', 'breakeven', 'expected-move', 'covered-call', 'roll'], tags: ['earnings', 'gap', 'semis'],
    checkpoints: [
      { label: 'Before earnings', date: '2024-02-21', context: 'NVDA ≈ $675, down ≈ 9% from its Feb 14 record close (≈ $739). Prices as traded before the June 2024 10:1 split. Options imply ≈ ±11% for the next day.',
        step: s('An ATM $675 straddle costs ≈ $75. Where are its breakevens at expiry?', [['be', '≈ $600 and ≈ $750'], ['one', 'Only at $675'], ['bad', '≈ $650 and ≈ $700']], 'be', 'Strike ± total premium. The stock must move about 11% before the straddle profits.') },
      { label: 'Next day', date: '2024-02-22', context: 'Q4 revenue ≈ $22.1B (+265% y/y). Q1 guide ≈ $24.0B. Closed ≈ $785 (+16.4%), adding ≈ $277B of value. You also hold shares with a short $750 call.',
        step: s('Your covered call is $35 ITM and you want to keep the shares. Choice?', [['roll', 'Roll the call up and out, paying a debit'], ['hold', 'Do nothing and hope it is not exercised']], 'roll', 'Rolling up and out buys back upside at a known cost. Doing nothing usually means the shares get called away.') },
      { label: 'After the move', date: '2024-02-23', context: 'Opened ≈ $808, closed ≈ $788. IV fell after the report.',
        step: s('Why did the straddle buyer profit despite IV crush?', [['real', 'Realized move (16%) exceeded the implied move (≈ 11%)'], ['iv', 'IV went up after the report']], 'real', 'A long straddle wins when the actual move beats the expected move. Most times it does not.') },
    ],
    outcome: 'A rare move above the [[expected-move]]. The [[straddle]] cleared its [[breakeven]]; the [[covered-call]] holder had to [[roll]] or give up the shares.',
  },
  {
    id: 'nvda-2024-08', ticker: 'NVDA', title: 'Beat, then fell', date: 'Aug 2024',
    summary: 'Revenue of $30.0B beat estimates and a $50B buyback was announced, yet NVDA fell 6.4% and then 9.5% more.',
    terms: ['iv-crush', 'vega', 'bull-call-spread', 'theta', 'earnings'], tags: ['earnings', 'volatility', 'semis'],
    checkpoints: [
      { label: 'Before earnings', date: '2024-08-28', context: 'NVDA ≈ $125.61 (after the June 10:1 split). It is the most watched report of the quarter. IV is high; options price a large move.',
        step: s('You are bullish. Which choice has the least exposure to IV crush?', [['bcs', 'Bull call spread'], ['atm', 'ATM weekly calls'], ['otm', 'Far-OTM weekly calls']], 'bcs', 'The short call has opposite vega, so the spread loses less when IV collapses after the report.') },
      { label: 'After hours', date: '2024-08-28', context: 'Q2 revenue ≈ $30.04B vs ≈ $28.7B expected. Q3 guide ≈ $32.5B. $50B buyback. Gross-margin outlook only "mid-70s". Stock indicated lower.',
        step: s('Results beat, but the stock falls. Why?', [['priced', 'Expectations were higher than the published estimates'], ['error', 'The market made an error']], 'priced', 'A beat that was already priced in can still disappoint. The reaction depends on the surprise versus hopes.') },
      { label: 'Two sessions later', date: '2024-09-03', context: 'Aug 29 closed ≈ $117.59 (−6.4%). Sep 3 closed ≈ $108.00 (−9.5%). IV is far below its pre-report level.',
        step: s('Your ATM calls lost on price and on IV. They expire in two weeks. Next?', [['cut', 'Close or cut per plan; do not add to "average down"'], ['add', 'Buy more, they are cheap now']], 'cut', 'Theta keeps eating the remaining value. A plan made before the report should decide, not hope.') },
    ],
    outcome: 'A beat that fell. Long calls lost to delta and [[iv-crush]] together; the [[bull-call-spread]] cut the [[vega]] hit.',
  },
  {
    id: 'aapl-2013-01', ticker: 'AAPL', title: 'Record quarter, falling stock', date: 'Jan 2013',
    summary: 'Record revenue of $54.5B was not enough: iPhone sales of 47.8M missed hopes and AAPL fell 12.4%.',
    terms: ['bear-put-spread', 'hedging', 'max-profit', 'earnings', 'gap'], tags: ['earnings', 'gap', 'tech'],
    checkpoints: [
      { label: 'Before earnings', date: '2013-01-23', context: 'AAPL ≈ $514, down ≈ 27% from its Sep 2012 record close (≈ $702). Prices as traded before the 2014 7:1 and 2020 4:1 splits. Puts are expensive.',
        step: s('You own shares and want a cheaper hedge than a plain put. Which?', [['ps', 'Put spread: buy a $500 put, sell a $450 put'], ['cc', 'Sell a covered call'], ['none', 'No hedge']], 'ps', 'The short put lowers the cost. Protection covers the fall from $500 to $450, which fits a normal gap.') },
      { label: 'After hours', date: '2013-01-23', context: 'Revenue ≈ $54.5B (record) and profit ≈ $13.1B (flat). iPhone units ≈ 47.8M, below hopes. Stock −10% after hours.',
        step: s('A record quarter, yet a big drop. Main reason?', [['growth', 'Slower growth and margins versus expectations'], ['random', 'Random noise']], 'growth', 'Prices reflect future growth. Flat profit and an iPhone miss lowered the outlook.') },
      { label: 'Next day', date: '2013-01-24', context: 'Closed ≈ $450.50 (−12.4%). Your $500/$450 put spread is near its max value ($50).',
        step: s('The put spread is close to max profit. Next?', [['close', 'Close it and decide fresh on a new hedge'], ['hold', 'Hold, it can still gain a lot']], 'close', 'A spread cannot pay more than its width. Below $450 the hedge stops working, so reset it.') },
    ],
    outcome: 'A record quarter and a 12% [[gap]] down. The put-spread [[hedging]] covered the drop at lower cost, and its [[max-profit]] showed where protection ended.',
  },
  {
    id: 'tsla-2024-10', ticker: 'TSLA', title: 'The best day since 2013', date: 'Oct 2024',
    summary: 'A profit beat and Musk\'s 20–30% growth forecast for 2025 sent TSLA up 21.9%, its best day since 2013.',
    terms: ['position-sizing', 'delta', 'iv-crush', 'vertical', 'profit-target'], tags: ['earnings', 'gap', 'ev'],
    checkpoints: [
      { label: 'Before earnings', date: '2024-10-23', context: 'TSLA ≈ $213.65. It fell 8.8% on Oct 11 after the robotaxi event. IV high; options price a large move.',
        step: s('You are bullish but unsure. How much do you risk on calls?', [['small', 'A small amount you can lose in full'], ['big', 'A large part of the account, the setup is clear']], 'small', 'Long calls can go to zero overnight. Size each event bet so a total loss is acceptable.') },
      { label: 'After hours', date: '2024-10-23', context: 'Adjusted EPS ≈ $0.72 vs ≈ $0.58 expected. Musk guided 20–30% vehicle growth for 2025. Stock indicated ≈ +12%. Your $230 calls are now ITM.',
        step: s('IV will collapse tomorrow. What now drives your call\'s value?', [['delta', 'Mostly delta and intrinsic value'], ['vega', 'Mostly vega']], 'delta', 'ITM after a gap, the call behaves more like stock. The IV loss is small next to the price gain.') },
      { label: 'Next day', date: '2024-10-24', context: 'Closed ≈ $260.48 (+21.9%). Your $230 calls are ≈ $30 ITM.',
        step: s('You want to keep some upside but lock in gains. Which?', [['vert', 'Sell a higher call to make a vertical, or take part of the profit'], ['hold', 'Hold all of it, the trend will continue']], 'vert', 'Selling a higher strike locks part of the gain and cuts risk. A profit target turns a paper win into a real one.') },
    ],
    outcome: 'A 22% gap up. Small [[position-sizing]] made the risk bearable; turning the call into a [[vertical]] locked the gain after [[iv-crush]].',
  },
  {
    id: 'googl-2024-04', ticker: 'GOOGL', title: 'The first dividend', date: 'Apr 2024',
    summary: 'A revenue beat, a first $0.20 dividend and a $70B buyback sent GOOGL up 10.2% and past $2T in value.',
    terms: ['straddle', 'calendar', 'ex-dividend', 'iv-crush', 'earnings'], tags: ['earnings', 'dividend', 'mega-cap'],
    checkpoints: [
      { label: 'Report day', date: '2024-04-25', context: 'META fell 10.6% today on a spending outlook. GOOGL closed ≈ $156 (−2.0%) and reports after the close. IV high.',
        step: s('You expect a big move but do not know the direction. Which fits that view?', [['strad', 'Small long straddle'], ['cal', 'Calendar spread at the money'], ['ic', 'Iron condor']], 'strad', 'A calendar and a condor profit if the stock stays still. Only the straddle matches a big-move view.') },
      { label: 'After hours', date: '2024-04-25', context: 'Revenue ≈ $80.5B vs ≈ $78.6B expected. EPS ≈ $1.89 vs ≈ $1.51. First dividend $0.20 a quarter and a $70B buyback.',
        step: s('How much does a $0.20 quarterly dividend change GOOGL option prices?', [['little', 'Very little: about a 0.5% yield'], ['lot', 'A lot: calls lose most of their value']], 'little', 'Expected dividends lower call prices and raise put prices, but a small dividend has a small effect.') },
      { label: 'Next day', date: '2024-04-26', context: 'Closed ≈ $171.95 (+10.2%). Value passed $2T. The put leg of your straddle is nearly worthless; the call leg is ITM.',
        step: s('IV has crushed and you got the move. Next?', [['close', 'Close the straddle and take the profit'], ['hold', 'Hold both legs for more']], 'close', 'The thesis was the event move. It happened; holding now is a new, different trade.') },
    ],
    outcome: 'A 10% [[gap]] after a strong report. The [[straddle]] matched the view; a [[calendar]] would have lost. The dividend added little to option pricing.',
  },
  {
    id: 'zm-2020-08', ticker: 'ZM', title: 'The pandemic blowout', date: 'Aug 2020',
    summary: 'Revenue up 355% and a raised forecast sent ZM up 40.8% in a day; two sessions later it was 16.7% lower.',
    terms: ['covered-call', 'iv', 'protective-put', 'earnings', 'gap'], tags: ['earnings', 'gap', 'software'],
    checkpoints: [
      { label: 'Before earnings', date: '2020-08-31', context: 'ZM closed ≈ $325, up ≈ 4.8× in 2020 (≈ $68 at the 2019 close). IV very high.',
        step: s('You have large gains in ZM shares. How do you limit loss but keep upside?', [['pp', 'Buy a protective put, accept the cost'], ['cc', 'Sell a covered call only'], ['none', 'No hedge, it only goes up']], 'pp', 'Only a put sets a floor. A covered call gives a small cushion and caps the upside you want.') },
      { label: 'Next day', date: '2020-09-01', context: 'Revenue ≈ $663.5M (+355%) vs ≈ $500.5M expected. FY guide ≈ $2.37–2.39B. Closed ≈ $457.69 (+40.8%). Value ≈ $129B. IV still high.',
        step: s('You hold shares and want income from the still-high IV. Which?', [['cc', 'Sell an OTM covered call'], ['np', 'Sell naked puts to add exposure']], 'cc', 'High IV means rich call premium. You trade some upside for income on shares you already own.') },
      { label: 'Tech sell-off', date: '2020-09-03', context: 'Closed ≈ $381.32, −16.7% in two sessions, as tech stocks fell.',
        step: s('Your covered-call premium offset part of the drop. What did it not do?', [['floor', 'It gave no floor below the premium received'], ['all', 'It fully protected the shares']], 'floor', 'A covered call only cushions by its premium. Downside protection needs a put.') },
    ],
    outcome: 'A 41% [[gap]] and a fast pullback. The [[protective-put]] set a floor; the [[covered-call]] earned income at high [[iv]] but did not protect.',
  },
  {
    id: 'docu-2022-06', ticker: 'DOCU', title: 'The billings cut', date: 'Jun 2022',
    summary: 'A profit miss and a lower billings outlook sent DOCU down 24.5%, then 10.3% more after downgrades.',
    terms: ['bid-ask', 'limit-order', 'mid-price', 'delta', 'roll'], tags: ['earnings', 'gap', 'software'],
    checkpoints: [
      { label: 'Before earnings', date: '2022-06-09', context: 'DOCU ≈ $87, down ≈ 72% from its Sep 2021 record close (≈ $310). Option spreads are wide before the report.',
        step: s('You want to buy puts. Say the quote is $4.00 bid / $4.80 ask. How do you enter?', [['lim', 'Limit order near the mid-price (≈ $4.40)'], ['mkt', 'Market order, fill at any price']], 'lim', 'A market order pays the full ask in a wide market. A limit near the mid often saves much of the spread.') },
      { label: 'After hours', date: '2022-06-09', context: 'Adjusted EPS ≈ $0.38 vs ≈ $0.46 expected. Revenue ≈ $588.7M, a small beat. Billings growth outlook cut to ≈ 7–8%. CFO change. Stock indicated ≈ −20%.',
        step: s('Your put is now deep ITM. How does it behave?', [['d1', 'Delta near −1: like short stock'], ['d0', 'Delta near 0']], 'd1', 'Deep ITM puts move almost dollar for dollar with the stock, so they carry full downside exposure.') },
      { label: 'Downgrades', date: '2022-06-13', context: 'Jun 10 closed ≈ $65.93 (−24.5%) after several downgrades. Jun 13 ≈ $59.12 (−10.3%).',
        step: s('Your puts have paid well. Next?', [['roll', 'Take part of the profit; roll the rest to a lower strike'], ['add', 'Buy many more puts after a 32% drop']], 'roll', 'Rolling down banks the gain and keeps a smaller, defined bet if the slide continues.') },
    ],
    outcome: 'A guidance-driven drop with follow-through. A [[limit-order]] near the [[mid-price]] cut entry cost; a [[roll]] banked the gains.',
  },
]
