import type { Moment } from '../shared/types'
import { s } from './helpers'

// Market moments, batch 3. Prices and IV figures are approximate, reconstructed for teaching (as traded at the time).
// Split notes: QQQ split 2:1 on 2000-03-20 (pre-split prices are given as split-adjusted, with the as-traded value noted).
// USO did a 1:8 reverse split on 2020-04-29; April 2020 USO prices below are as traded before that split.
export const MOMENTS_B3: Moment[] = [
  {
    id: 'flash-2010-05', ticker: 'SPX', title: 'The flash crash', date: 'May 2010',
    summary: 'Within minutes the Dow fell ≈ 9% intraday, some stocks printed at one cent, and most of the drop came back before the close.',
    terms: ['limit-order', 'stop-loss', 'bid-ask', 'liquidity', 'slippage', 'vix'], tags: ['crash', 'liquidity', 'volatility'],
    checkpoints: [
      { label: 'Nervous morning', date: '2010-05-06', context: 'SPX ≈ 1,166 at the prior close. Greek debt crisis on the news. VIX ≈ 25 and rising. Liquidity in index futures already thin.',
        step: s('You keep a stop-loss on your stock and plan to sell options fast if markets slide. Which order type protects your price?', [['lmt', 'Limit orders, with a price you accept'], ['mkt', 'Market orders, to be sure of a fill'], ['stop', 'Plain stop orders, they fill at the stop']], 'lmt', 'A stop becomes a market order when hit. A market order takes any price that is there. Only a limit order sets the worst price.') },
      { label: 'The plunge', date: '2010-05-06', context: '≈ 2:30–2:45 pm: a sell program of ≈ 75,000 E-mini contracts (≈ $4.1B) hits a thin market. Dow −998 points intraday (≈ −9%). Accenture traded at $0.01; P&G fell from ≈ $62 to ≈ $39.',
        step: s('Option quotes on your names now show bids near zero and asks far above fair value. Best action?', [['wait', 'Do not trade into quotes with no real market'], ['dump', 'Sell everything at the bid before it gets worse'], ['buy', 'Buy calls at the ask: they are on sale']], 'wait', 'In a liquidity vacuum the bid–ask spread is the real loss. Quotes that far apart are not prices you must accept.') },
      { label: 'Close', date: '2010-05-06', context: 'SPX closed ≈ 1,128 (−3.2%) after an intraday low ≈ 1,066. VIX closed ≈ 32.8 (+32%). Exchanges later broke trades more than 60% from reference prices.',
        step: s('A trader\'s stop sold shares at $20 that closed at $40. The trade was not broken. Lesson?', [['plan', 'Stops give no price limit; use stop-limits or puts for protection'], ['luck', 'Bad luck, nothing to change']], 'plan', 'A stop-loss can fill far from its trigger in a fast market. A put gives a fixed floor; a stop-limit caps the fill price.') },
    ],
    outcome: 'Most of the drop came back in minutes, but [[stop-loss]] and market orders filled at absurd prices. [[limit-order|Limit orders]] and real [[liquidity]] decided the outcome; new single-stock circuit breakers followed in June 2010.',
  },
  {
    id: 'lehman-2008-09', ticker: 'XLF', title: 'Lehman goes bankrupt', date: 'Sep 2008',
    summary: 'Lehman Brothers filed the largest bankruptcy in US history; bank stocks fell hard, AIG needed a rescue, and policy moves then caused a violent snap-back.',
    terms: ['tail-risk', 'correlation', 'long-put', 'iv', 'hedging'], tags: ['crisis', 'banks', 'volatility'],
    checkpoints: [
      { label: 'Friday before', date: '2008-09-12', context: 'XLF ≈ $17.18. SPX ≈ 1,252. VIX ≈ 25.7. Talks to sell Lehman over the weekend are under way. No buyer is confirmed.',
        step: s('You hold several bank stocks into a weekend with a possible failure. Best step before the close?', [['hedge', 'Buy XLF puts now, sized to the basket'], ['wait', 'Wait for Monday and react to the news'], ['cc', 'Sell covered calls for income']], 'hedge', 'The decision comes while markets are closed. Protection must be bought before the gap, not after it.') },
      { label: 'Bankruptcy Monday', date: '2008-09-15', context: 'Lehman filed Chapter 11 (≈ $600B+ assets). Dow −504 (−4.4%). SPX ≈ 1,193 (−4.7%). XLF ≈ $15.51 (−9.7%). VIX ≈ 31.7.',
        step: s('Some funds held OTC derivatives with Lehman as the counterparty. What protected holders of listed options?', [['occ', 'Central clearing: the OCC stands behind listed contracts'], ['none', 'Nothing: all derivatives with Lehman were frozen']], 'occ', 'Listed options are guaranteed by the clearing house. OTC trades depended on Lehman itself, so they were stuck in the bankruptcy.') },
      { label: 'Policy shock', date: '2008-09-19', context: 'AIG got an ≈ $85B Fed loan (Sep 16). SEC banned short sales of financials; the Treasury outlined a bank rescue plan. XLF opened ≈ $19.66, closed ≈ $18.18 (+12%). XLF had closed ≈ $15.07 on Sep 17.',
        step: s('Your XLF puts lost much of their gain in two days. What does this teach?', [['policy', 'In crises, policy can reverse prices fast: take some profit on spikes'], ['wrong', 'The hedge was a mistake']], 'policy', 'A hedge is insurance, not a bet. Policy news can cause sharp rallies, so bank part of a large hedge gain when it is there.') },
    ],
    outcome: 'A classic [[tail-risk]] weekend. Bank stocks moved together ([[correlation]] near 1), listed options were safe from counterparty failure, and policy turned the move in days.',
  },
  {
    id: 'spx-2008-10', ticker: 'SPX', title: 'Panic October', date: 'Oct 2008',
    summary: 'After the worst week since the 1930s, the S&P 500 jumped ≈ 11.6% in a day, then fell ≈ 9% two days later as VIX stayed near 70.',
    terms: ['vix', 'short-strangle', 'position-sizing', 'max-loss', 'iron-condor', 'vega'], tags: ['crash', 'crisis', 'volatility'],
    checkpoints: [
      { label: 'Worst week', date: '2008-10-10', context: 'SPX ≈ 899 after ≈ −18% for the week; intraday low ≈ 840. VIX closed ≈ 70. Credit markets frozen.',
        step: s('Option premiums are huge. A friend wants to sell naked SPX strangles "because IV must fall". Better approach?', [['ic', 'If selling at all: small iron condor with defined max loss'], ['ns', 'Sell large naked strangles for the premium'], ['all', 'Use all margin while premium is rich']], 'ic', 'High IV pays more because daily moves are huge. Only wings cap the loss when a 10% day comes.') },
      { label: 'Record rally', date: '2008-10-13', context: 'Governments announced bank rescue plans. SPX +11.6% to ≈ 1,003, the best day since the 1930s. Dow +936. VIX fell to ≈ 55.',
        step: s('Your short calls are now deep ITM after one day. What went wrong?', [['size', 'High-vol regimes move both ways; size was too big for one 11% day'], ['only', 'Rallies cannot happen in a crash']], 'size', 'Crash markets have the biggest up days too. Size each trade so the worst one-day move in either direction is survivable.') },
      { label: 'Back down', date: '2008-10-15', context: 'SPX −9.0% to ≈ 908, almost all of the rally gone. VIX back to ≈ 69. VIX hit ≈ 89.5 intraday on Oct 24.',
        step: s('You bought ATM straddles at VIX ≈ 55 to "trade the swings". What decides profit?', [['real', 'Realized moves must beat the high implied vol you paid'], ['dir', 'Only the direction of the next move']], 'real', 'A straddle at high IV is a bet that actual moves will be even bigger. Big moves alone are not enough; vega also falls if fear eases.') },
    ],
    outcome: 'Moves of ±10% in days. [[position-sizing]] and defined [[max-loss]] mattered more than direction; VIX near 70 was expensive for buyers and dangerous for naked sellers.',
  },
  {
    id: 'spx-1987-10', ticker: 'SPX', title: 'Black Monday', date: 'Oct 1987',
    summary: 'The S&P 500 fell ≈ 20.5% in one day, still its worst day ever; index options already traded, and the crash created the modern put skew.',
    terms: ['tail-risk', 'protective-put', 'skew', 'volatility-smile', 'margin'], tags: ['crash', 'history', 'volatility'],
    checkpoints: [
      { label: 'Friday sell-off', date: '1987-10-16', context: 'SPX ≈ 283 (−5.2% on the day, ≈ −9% for the week). Many funds rely on "portfolio insurance": selling futures as prices fall.',
        step: s('A fund relies on selling futures if the market drops. What is the weak point vs owning index puts?', [['liq', 'It needs buyers to be there in a crash; a put does not'], ['same', 'No difference, both hedge the same way']], 'liq', 'Dynamic hedging only works with liquid markets. A bought put has a fixed strike, paid in advance, whatever the market does.') },
      { label: 'Black Monday', date: '1987-10-19', context: 'SPX ≈ 225 (−20.5%). Dow −508 (−22.6%). Futures traded at deep discounts. The VXO index closed ≈ 150.',
        step: s('A trader had sold many OTM index puts for "free money". Today he faces…', [['call', 'Margin calls and losses many times the premium'], ['small', 'A small loss capped at the premium']], 'call', 'A short put loses down to zero. Losses of 20 times the premium collected can wipe out an account in one day.') },
      { label: 'Next day', date: '1987-10-20', context: 'SPX intraday low ≈ 216, closed ≈ 237 (+5.3%). VXO hit ≈ 173 intraday. The Fed promised liquidity.',
        step: s('Why do OTM index puts still trade at a higher IV than equal OTM calls today?', [['skew', 'Since 1987, the market prices crash risk: put skew'], ['math', 'Black-Scholes requires it']], 'skew', 'Before 1987 the smile was nearly flat. After it, sellers demand more for downside tails, so OTM puts carry higher IV.') },
    ],
    outcome: 'Portfolio insurance failed when [[liquidity]] vanished; bought puts paid. The crash gave birth to the index put [[skew]] that still exists.',
  },
  {
    id: 'uso-2020-04', ticker: 'USO', title: 'Oil below zero', date: 'Apr 2020',
    summary: 'The May WTI contract settled at −$37.63; the USO oil ETF did not go negative but fell ≈ 25% the next day and then reverse-split 1:8.',
    terms: ['contango', 'underlying', 'settlement', 'leverage', 'liquidity'], tags: ['commodities', 'crash', 'structure'],
    checkpoints: [
      { label: 'Cheap oil?', date: '2020-04-17', context: 'May WTI ≈ $18. USO ≈ $4.21 (as traded, before the 1:8 reverse split). Storage at Cushing nearly full. Futures in steep contango. Retail money poured into USO.',
        step: s('You think oil "cannot go lower" and want USO calls. What must you check first?', [['what', 'What USO holds: futures that it must roll'], ['cheap', 'Nothing: USO tracks the oil spot price'], ['size', 'Only the strike with the lowest premium']], 'what', 'USO owns futures, not barrels. In steep contango it sells cheap expiring contracts and buys dearer ones, so it can lose while spot is flat.') },
      { label: 'Below zero', date: '2020-04-20', context: 'May WTI settled at −$37.63, the first negative price ever. USO had moved most holdings to later months: ≈ $3.75 (−11%).',
        step: s('Why did USO not go negative with the May contract?', [['later', 'It held later-month futures, and a fund share cannot fall below zero'], ['halt', 'Trading in USO was halted']], 'later', 'The ETF owned other contracts. Its holders can lose all their money but no more; futures holders had no such floor.') },
      { label: 'Reverse split', date: '2020-04-22', context: 'USO fell ≈ 25% on Apr 21 to ≈ $2.81, then ≈ $2.51. A 1:8 reverse split was announced, effective Apr 29.',
        step: s('You hold USO calls. What happens to them in the reverse split?', [['adj', 'The OCC adjusts them: non-standard deliverable, often thin markets'], ['void', 'They are cancelled'], ['x8', 'Strikes stay the same; value jumps 8×']], 'adj', 'Splits do not create or destroy value. Adjusted contracts change their deliverable, and they often trade with wide spreads.') },
    ],
    outcome: 'A lesson in what the [[underlying]] really is. [[contango]] and storage, not the headline spot price, drove USO; adjusted options after the split had poor [[liquidity]].',
  },
  {
    id: 'viac-2021-03', ticker: 'VIAC', title: 'The Archegos unwind', date: 'Mar 2021',
    summary: 'A hidden, highly leveraged family office was forced to sell; ViacomCBS fell from a $100 record to ≈ $48 in four sessions.',
    terms: ['leverage', 'margin', 'collar', 'protective-put', 'position-sizing'], tags: ['crash', 'leverage', 'single-stock'],
    checkpoints: [
      { label: 'Record high', date: '2021-03-22', context: 'VIAC closed at a record ≈ $100.34 after a big run in early 2021. After the close it announced a ≈ $3B stock offering.',
        step: s('You hold VIAC with a large gain. New share supply is coming. Lowest-cost way to protect most of the gain?', [['collar', 'A collar: buy a put, sell an OTM call to fund it'], ['none', 'Hold, the trend is strong'], ['margin', 'Buy more on margin']], 'collar', 'A collar locks a floor at little net cost. It gives up some upside, which is fair after a big run with new supply ahead.') },
      { label: 'Offering flops', date: '2021-03-24', context: 'Offering priced at $85. VIAC closed ≈ $70.10 (−23%). A large holder was using swaps with heavy leverage, unknown to the market.',
        step: s('When a stock falls far below an offering price, who is most at risk?', [['lev', 'Leveraged holders: margin calls force more selling'], ['nobody', 'Nobody, long-term holders will step in']], 'lev', 'Leverage turns a price drop into forced selling. Forced sellers do not care about price, so the drop can feed itself.') },
      { label: 'Block sales', date: '2021-03-26', context: 'Banks dumped huge blocks of Archegos positions. VIAC closed ≈ $48.23 (−27% on the day, ≈ −52% from the record).',
        step: s('What would have kept one position from ruining the account?', [['size', 'Small size and no margin on a single stock'], ['stop', 'A stop-loss at −10%']], 'size', 'Stops fill wherever the market is during block selling. Only size and low leverage limit the damage from a single name.') },
    ],
    outcome: 'Hidden [[leverage]] became forced selling. A [[collar]] or [[protective-put]] set a floor; [[position-sizing]] decided who survived.',
  },
  {
    id: 'cs-2023-03', ticker: 'CS', title: 'Credit Suisse collapses', date: 'Mar 2023',
    summary: 'Days after SVB, Credit Suisse lost its biggest backer\'s support; a weekend deal sold it to UBS for CHF 0.76 per share.',
    terms: ['gap', 'tail-risk', 'liquidity', 'expected-value', 'position-sizing'], tags: ['banks', 'crisis', 'contagion'],
    checkpoints: [
      { label: 'Backer says no', date: '2023-03-15', context: 'Its largest shareholder, Saudi National Bank, ruled out more money. CS fell more than 30% intraday and closed −24% at a record low. European banks sold off.',
        step: s('CS calls are cheap in dollars. You want to bet on a rescue rally. Key point?', [['ev', 'Cheap is not good value: size for a total loss'], ['safe', 'A big bank is too big to fall more'], ['lev', 'Buy many to make it count']], 'ev', 'Low premium does not mean high expected value. Treat it as money you can lose in full, and keep it small.') },
      { label: 'Central bank loan', date: '2023-03-16', context: 'Swiss National Bank offered up to CHF 50B of liquidity. CS shares jumped more than 30% at the open, closed +19%.',
        step: s('Does the central bank loan make the shares safe?', [['no', 'No: liquidity is not solvency; depositors can keep leaving'], ['yes', 'Yes, the risk is now gone']], 'no', 'A loan buys time but does not fix trust. Bank runs can continue after a backstop.') },
      { label: 'Weekend deal', date: '2023-03-19', context: 'Sunday: UBS agreed to buy CS for ≈ CHF 3B, CHF 0.76 per share. ≈ CHF 16B of AT1 bonds written to zero. On Mar 20 CS shares fell ≈ 55%.',
        step: s('The key decision came on a Sunday. Lesson for open option positions in a crisis?', [['wknd', 'Weekend gap risk: hold only risk you can carry through a close'], ['mon', 'You can always adjust on Monday morning']], 'wknd', 'Rescues and failures are decided while markets are closed. Monday opens at the new price; there is no chance to adjust in between.') },
    ],
    outcome: 'A weekend [[gap]] set the price. Cheap lottery calls had poor [[expected-value]], and the backstop did not stop the run. Small size was the only protection.',
  },
  {
    id: 'coin-2022-11', ticker: 'COIN', title: 'The FTX collapse', date: 'Nov 2022',
    summary: 'FTX went from a rescue offer to bankruptcy in five days; bitcoin fell ≈ 23% and Coinbase dropped ≈ 19% in two sessions.',
    terms: ['correlation', 'gap', 'protective-put', 'iv', 'cpi'], tags: ['crypto', 'crisis', 'contagion'],
    checkpoints: [
      { label: 'Binance sells FTT', date: '2022-11-07', context: 'On Sunday Nov 6, Binance said it would sell its FTT tokens. COIN ≈ $56.97. BTC ≈ $20.6K. Withdrawals from FTX surging.',
        step: s('You own COIN. Crypto trades 24/7, but COIN options trade only in US hours. Best step today?', [['put', 'Buy COIN puts now, before more overnight news'], ['wait', 'Wait to see what crypto does tonight']], 'put', 'Crypto news arrives at night and on weekends. COIN can gap at the open, so the hedge must be in place before the close.') },
      { label: 'Rescue, then panic', date: '2022-11-08', context: 'Binance signed a deal to buy FTX. FTT fell ≈ 75% in a day. BTC low ≈ $17.6K. COIN closed ≈ $50.83 (−11%).',
        step: s('Coinbase had no stated FTX exposure, yet it fell with crypto. Why?', [['corr', 'In a panic, correlation across crypto assets goes toward 1'], ['news', 'Coinbase announced losses']], 'corr', 'Investors sell the whole theme first and ask questions later. Hedges based on low normal correlation fail in a panic.') },
      { label: 'Deal dropped', date: '2022-11-09', context: 'Binance walked away. COIN ≈ $45.98 (−9.5%). BTC ≈ $15.9K. A US CPI report is due tomorrow morning.',
        step: s('Your COIN puts are up a lot and IV is high, with CPI due tomorrow. Next?', [['take', 'Take part of the profit before the scheduled event'], ['hold', 'Hold all of them, the panic will continue']], 'take', 'Scheduled data can reverse a panic. COIN rose ≈ 11% after a soft CPI on Nov 10 and ≈ 13% on Nov 11, the day FTX filed for bankruptcy.') },
    ],
    outcome: 'A 24/7 market moved a stock that trades 6.5 hours a day. [[correlation]] went to 1 in the panic, and a [[cpi]] surprise reversed it fast.',
  },
  {
    id: 'spx-2021-09', ticker: 'SPX', title: 'The Evergrande scare', date: 'Sep 2021',
    summary: 'Fear of a default by China\'s most indebted developer hit global stocks for one day; within three days the S&P 500 was back above its prior close.',
    terms: ['vix', 'vega', 'iv-crush', 'bull-put-spread', 'fomc'], tags: ['macro', 'volatility', 'china'],
    checkpoints: [
      { label: 'Warnings', date: '2021-09-17', context: 'SPX ≈ 4,433. VIX ≈ 20.8. Evergrande warned it might default. A Fed meeting ends Sep 22.',
        step: s('You hold an index portfolio. VIX is near 21. Cost-aware hedge?', [['ps', 'A put spread: lower cost, protects a defined range'], ['none', 'No hedge: China does not affect the US'], ['many', 'Many short-dated OTM puts']], 'ps', 'A put spread cuts the cost of the hedge when IV is already up, and still pays in a normal sell-off.') },
      { label: 'Monday rout', date: '2021-09-20', context: 'Hang Seng −3.3%. SPX −1.7% to ≈ 4,358 (low ≈ 4,306). Dow −614. VIX hit ≈ 28.8 intraday, closed ≈ 25.7.',
        step: s('You want to sell premium at the higher IV. Which trade fits?', [['bps', 'A small bull put spread below support'], ['np', 'Large naked puts'], ['ns', 'A short strangle sized on margin']], 'bps', 'Selling rich IV can pay, but the scare might spread. A spread caps the loss if the selling continues.') },
      { label: 'Fear fades', date: '2021-09-23', context: 'Evergrande missed an ≈ $83.5M bond coupon (30-day grace period). After the Fed meeting, SPX ≈ 4,449, above the Sep 17 close. VIX ≈ 18.6.',
        step: s('VIX fell from ≈ 25.7 to ≈ 18.6 in three days. What happened to puts bought on Monday?', [['crush', 'Lost value fast: lower price plus IV crush'], ['same', 'Kept their value, the coupon was missed']], 'crush', 'Puts bought in a spike pay for high IV. When fear eases, vega losses add to the delta losses.') },
    ],
    outcome: 'A one-day scare. Buyers of panic puts suffered [[iv-crush]]; small [[bull-put-spread|bull put spreads]] sold into the spike kept defined risk and earned the fade.',
  },
  {
    id: 'spx-2018-12', ticker: 'SPX', title: 'The Christmas Eve low', date: 'Dec 2018',
    summary: 'The S&P 500 fell ≈ 19.8% from its September record by Christmas Eve, then jumped ≈ 5% on Dec 26.',
    terms: ['bid-ask', 'liquidity', 'bear-put-spread', 'position-sizing', 'vix'], tags: ['crash', 'holiday', 'volatility'],
    checkpoints: [
      { label: 'Before the holiday', date: '2018-12-21', context: 'SPX ≈ 2,417, −17.5% from the Sep 20 record ≈ 2,931. Fed hiked on Dec 19. A government shutdown starts at midnight. Dec 24 is a half-day.',
        step: s('You must adjust options on the half-day session. Best practice?', [['lmt', 'Limit orders near mid; expect wide spreads in thin trade'], ['mkt', 'Market orders: speed matters most']], 'lmt', 'Holiday sessions have few market makers. Spreads widen, and market orders pay the full width.') },
      { label: 'Christmas Eve', date: '2018-12-24', context: 'SPX −2.7% to ≈ 2,351, ≈ −19.8% from the record. VIX ≈ 36. The Treasury Secretary had called bank CEOs over the weekend, which worried markets more.',
        step: s('You are bearish and want more downside exposure here. Defined-risk choice?', [['bps', 'A bear put spread'], ['short', 'Short more stock or futures'], ['nc', 'Sell naked calls']], 'bps', 'After a near-20% fall, rebounds can be violent. A bear put spread caps the loss if the market snaps back.') },
      { label: 'Boxing Day', date: '2018-12-26', context: 'SPX +5.0% to ≈ 2,468. Dow +1,086, its first 1,000-point gain ever. VIX ≈ 30.4.',
        step: s('What does a +5% day in a falling market teach about sizing?', [['both', 'High-vol markets move hard both ways; size for the worst day in either direction'], ['top', 'The bottom is in, so size up']], 'both', 'Bear-market rallies are some of the biggest up days. Bearish positions must survive them.') },
    ],
    outcome: 'Thin holiday [[liquidity]] made the low and the rally sharper. Defined-risk bears survived the snap-back; [[position-sizing]] for both directions mattered.',
  },
  {
    id: 'tlt-2014-10', ticker: 'TLT', title: 'The Treasury flash rally', date: 'Oct 2014',
    summary: 'The 10-year Treasury yield fell ≈ 16 bp and bounced back within 12 minutes, in the deepest bond market in the world, with no clear news.',
    terms: ['liquidity', 'bid-ask', 'naked-call', 'bear-call-spread', 'tail-risk'], tags: ['bonds', 'liquidity', 'volatility'],
    checkpoints: [
      { label: 'Crowded short', date: '2014-10-14', context: '10-year yield ≈ 2.21%. TLT ≈ $121.6. Many funds were positioned for higher yields (lower bond prices).',
        step: s('You expect TLT to fall and want to sell calls. Which structure fits a crowded trade?', [['bcs', 'Bear call spread: the long call caps the loss'], ['nc', 'Naked calls: bonds never move fast']], 'bcs', 'Crowded positions can unwind all at once. Even "safe" assets can have tail moves.') },
      { label: 'The 12 minutes', date: '2014-10-15', context: 'Weak retail sales at 8:30 am. Then, 9:33–9:45 am, the 10-year yield fell ≈ 16 bp and reversed. Day range ≈ 2.23% → 1.86%. TLT hit ≈ $127.7 (+5%).',
        step: s('Quotes on TLT options blow out. You must close a short call. Best order?', [['lmt', 'A limit order, worked patiently'], ['mkt', 'A market order right now']], 'lmt', 'When dealers step back, the bid–ask gap is huge. A market order pays the worst quote in the book.') },
      { label: 'Close', date: '2014-10-15', context: '10-year yield closed ≈ 2.15%, only ≈ 6 bp lower on the day. TLT ≈ $122.5. A joint agency report later found no single cause.',
        step: s('What is the main lesson from a flash move in the "safest" market?', [['def', 'Liquidity can vanish anywhere; use defined risk'], ['safe', 'Treasuries are always liquid, so it does not matter']], 'def', 'Liquidity is a condition, not a property of an asset. Defined-risk structures survive moves you cannot trade through.') },
    ],
    outcome: 'Even US Treasuries lost [[liquidity]] for minutes. Naked short options faced an unhedgeable [[tail-risk]]; spreads and limit orders limited the damage.',
  },
  {
    id: 'qqq-2022-02', ticker: 'QQQ', title: 'The invasion reversal', date: 'Feb 2022',
    summary: 'Russia invaded Ukraine; the Nasdaq opened ≈ −3.5% and closed +3.3% as VIX fell from ≈ 37.5 to ≈ 30.',
    terms: ['iv-crush', 'vix', 'vega', 'expected-move', 'gap'], tags: ['macro', 'war', 'volatility'],
    checkpoints: [
      { label: 'Tension peak', date: '2022-02-23', context: 'QQQ ≈ $329. VIX ≈ 31. An invasion looks likely. Index put IV is already high.',
        step: s('You want protection for a tech portfolio. IV is high. Most cost-aware hedge?', [['spread', 'A put spread or a smaller position'], ['otm', 'Many short-dated OTM puts'], ['none', 'Nothing, war news is always bullish']], 'spread', 'When a known risk is already in prices, puts are dear. Selling a lower strike cuts the cost.') },
      { label: 'Invasion open', date: '2022-02-24', context: 'Russia attacked overnight. QQQ opened ≈ $319 (−3.2%). VIX ≈ 37.5 at the open. Brent topped $100 for the first time since 2014.',
        step: s('You did not hedge. Buy ATM puts at the open?', [['no', 'Not at peak IV after the gap; reduce size instead'], ['yes', 'Yes, the war will push prices lower']], 'no', 'At the open you pay the gap plus the highest IV of the day. If fear fades, the put loses on both.') },
      { label: 'Reversal close', date: '2022-02-24', context: 'QQQ closed ≈ $340.5 (+3.4%). Nasdaq +3.3%. SPX +1.5%. VIX closed ≈ 30.3.',
        step: s('Puts bought at the open lost a lot even with war news. Main cause?', [['both', 'The rally plus IV crush after the known event'], ['theta', 'Only time decay']], 'both', 'Once the feared event happens, uncertainty falls. Delta and vega both work against late put buyers.') },
    ],
    outcome: 'The feared event caused a "sell the rumor, buy the news" reversal. Late put buyers suffered [[iv-crush]]; hedges set up before the [[gap]] worked.',
  },
  {
    id: 'qqq-2000-03', ticker: 'QQQ', title: 'The dot-com peak', date: 'Mar 2000',
    summary: 'The Nasdaq peaked at ≈ 5,049 in March 2000, fell ≈ 34% by mid-April, and lost ≈ 78% by October 2002.',
    terms: ['collar', 'leaps', 'trend', 'protective-put', 'margin'], tags: ['bubble', 'crash', 'tech'],
    checkpoints: [
      { label: 'The peak', date: '2000-03-10', context: 'Nasdaq closed at a record ≈ 5,049 (up ≈ 86% in 1999). QQQ ≈ $114.5 split-adjusted (≈ $229 as traded before its 2:1 split on Mar 20).',
        step: s('Your tech stocks have huge gains. You still think tech can rise. How do you keep upside and limit loss?', [['collar', 'A collar or protective puts on part of the gains'], ['margin', 'Add more on margin'], ['sell', 'Sell covered calls with no downside cover']], 'collar', 'A collar keeps a range of upside and sets a floor. Covered calls only give a small cushion against a big fall.') },
      { label: 'Black Friday', date: '2000-04-14', context: 'Nasdaq −9.7% to ≈ 3,321, ≈ −34% from the peak. QQQ ≈ $80.4. Margin calls hit many leveraged accounts.',
        step: s('A trader on margin must sell at the lows. What gave option holders more time?', [['defined', 'Long puts or collars: no margin call on a defined position'], ['same', 'Nothing, everyone had to sell']], 'defined', 'A paid-for put or a collar has a known worst case. Margin debt forces sales at the worst moment.') },
      { label: 'Bear bottom', date: '2002-10-09', context: 'Nasdaq ≈ 1,114, ≈ −78% from the peak. QQQ ≈ $20.',
        step: s('Some "buy the dip" LEAPS calls bought in 2000 expired worthless. Lesson?', [['trend', 'Long bear trends can outlast even long-dated options'], ['leaps', 'LEAPS cannot lose money']], 'trend', 'A LEAPS call has more time, but not unlimited time. Size dip-buying for the chance the trend lasts years.') },
    ],
    outcome: 'A bubble peak and a multi-year [[trend]] down. [[collar|Collars]] and puts set floors; [[margin]] forced sales; even [[leaps]] ran out of time.',
  },
  {
    id: 'coin-2024-01', ticker: 'COIN', title: 'The bitcoin ETF approval', date: 'Jan 2024',
    summary: 'The SEC approved spot bitcoin ETFs after a fake approval post a day earlier; bitcoin and Coinbase then fell as traders sold the news.',
    terms: ['iv-crush', 'covered-call', 'expected-move', 'iv', 'long-call'], tags: ['crypto', 'event', 'sell-the-news'],
    checkpoints: [
      { label: 'Fake post', date: '2024-01-09', context: 'COIN ≈ $152 (≈ $186 on Dec 28). Shortly after 4 pm, the SEC X account was hacked to post a fake approval; BTC jumped ≈ $1,000 and fell back when it was denied.',
        step: s('A headline says the approval is out, but it is after hours. Best response?', [['verify', 'Wait for the official source before trading'], ['buy', 'Buy calls in the after-hours session now']], 'verify', 'Fake headlines move prices for minutes. Confirm the source before risking money in thin after-hours trade.') },
      { label: 'Real approval', date: '2024-01-10', context: 'The SEC approved 11 spot bitcoin ETFs after the close. COIN ≈ $151. Option IV elevated into the event. Trading starts Jan 11.',
        step: s('You own COIN and expect "sell the news". IV is high. Fitting trade?', [['cc', 'Sell covered calls to collect the rich premium'], ['lc', 'Buy more calls at the high IV']], 'cc', 'High pre-event IV favors selling premium against shares you own. Call buyers need a move larger than the expected move.') },
      { label: 'Sell the news', date: '2024-01-12', context: 'ETF trading began with ≈ $4.6B volume. BTC hit ≈ $49K on Jan 11, then ≈ $42.9K. COIN opened ≈ $159 on Jan 11, closed ≈ $141 (−6.7%), then ≈ $131 (−7.4%). By Jan 23: COIN ≈ $124, BTC ≈ $39.8K.',
        step: s('Call buyers were right about approval but lost money. Why?', [['priced', 'Approval was already priced in; IV crush and selling followed'], ['wrong', 'The ETFs were not approved']], 'priced', 'A known, expected event is in the price before it happens. After it, IV falls and early buyers take profits.') },
    ],
    outcome: 'A textbook sell-the-news move. Being right on the event was not enough: [[iv-crush]] and a priced-in rally beat late [[long-call|call buyers]], while [[covered-call|covered calls]] earned the rich premium.',
  },
]
