import type { Moment } from '../shared/types'
import { s } from './helpers'

// Market moments, batch 2. Prices and IV figures are approximate, reconstructed for teaching (as traded at the time).
export const MOMENTS_B2: Moment[] = [
  {
    id: 'cpi-2022-09', ticker: 'SPX', title: 'The hot CPI print', date: 'Sep 2022',
    summary: 'August CPI came in at 8.3% vs 8.1% expected; the S&P 500 fell ≈ 4.3% in one day.',
    terms: ['cpi', 'expected-move', 'bear-put-spread', 'standard-deviation', 'vix'], tags: ['macro', 'inflation', 'event'],
    checkpoints: [
      { label: 'Night before CPI', date: '2022-09-12', context: 'SPX ≈ 4,110 after a four-day rally. VIX ≈ 23.9. CPI is due at 8:30 ET, before the open. Short-dated SPX options carry extra event premium.',
        step: s('You hold a large stock portfolio into the CPI print. Best plan?', [['ps', 'Small SPX put spread that covers the release'], ['none', 'No hedge, the rally shows inflation is peaking'], ['sp', 'Sell puts to collect the event premium']], 'ps', 'A scheduled data release is a known gap risk. A put spread defines the cost; the short leg cuts the price of the extra event premium.') },
      { label: 'CPI day', date: '2022-09-13', context: 'CPI 8.3% y/y vs 8.1% expected; core 6.3% vs 6.1%. SPX closed ≈ 3,933 (−4.3%). VIX ≈ 27.3.',
        step: s('The drop was larger than the implied move. What does that tell you about the expected move?', [['sd', 'It is about one standard deviation, not a cap'], ['wrong', 'The options market priced it wrong, so ignore it next time']], 'sd', 'The expected move is a one-SD estimate. Larger moves happen about one time in three, so size every event trade for that.') },
      { label: 'End of week', date: '2022-09-16', context: 'SPX ≈ 3,873, down ≈ 5.8% from Monday. VIX ≈ 26.3. Your put spread is near its full width.',
        step: s('The put spread is close to max value. Next?', [['close', 'Close it or roll down: little profit is left'], ['hold', 'Hold to expiry for the last few dollars']], 'close', 'A spread cannot pay more than its width. Near max value, the remaining reward is small and the risk of a bounce is not.') },
    ],
    outcome: 'A hot [[cpi]] print moved SPX far beyond one [[standard-deviation]]. Hedges bought before the release worked; a [[bear-put-spread]] near full value was a clear time to take profit.',
  },
  {
    id: 'cpi-2022-11', ticker: 'SPX', title: 'The CPI relief rally', date: 'Nov 2022',
    summary: 'October CPI came in at 7.7%, below forecasts; the S&P 500 jumped ≈ 5.5%, its best day since 2020.',
    terms: ['cpi', 'vega', 'delta', 'bear-call-spread', 'gap'], tags: ['macro', 'inflation', 'rally'],
    checkpoints: [
      { label: 'Day before CPI', date: '2022-11-09', context: 'SPX ≈ 3,749 (−2.1% on the day). VIX ≈ 26.1. Midterm results still unclear. Sentiment bearish.',
        step: s('You expect a hot CPI and lower prices. Which bearish trade keeps your risk defined?', [['bcs', 'Bear call spread or put spread, small size'], ['nc', 'Sell naked SPX calls for the high premium']], 'bcs', 'A data surprise can gap the market either way. Naked short calls have no cap if the gap is up.') },
      { label: 'CPI day', date: '2022-11-10', context: 'CPI 7.7% y/y vs ≈ 7.9% expected. SPX closed ≈ 3,956 (+5.5%), Nasdaq +7.3%. VIX fell to ≈ 23.5.',
        step: s('A trader held long SPX puts. Why did they lose so much in one day?', [['both', 'Delta and vega both hurt: price up, IV down'], ['theta', 'Mostly time decay']], 'both', 'Index IV usually falls as stocks rally. Long puts lose on price and on volatility at the same time.') },
      { label: 'Day after', date: '2022-11-11', context: 'SPX ≈ 3,993 (+0.9%). VIX ≈ 22.5. Many traders now want calls.',
        step: s('You missed the rally and want upside now. Best approach?', [['spread', 'Small call spread with a plan, or wait'], ['otm', 'Buy many cheap OTM weekly calls']], 'spread', 'Chasing after a gap pays elevated IV for a move that already happened. Define the risk and keep the size small.') },
    ],
    outcome: 'A soft [[cpi]] print caused an up-[[gap]]. Long puts lost on [[delta]] and [[vega]] together; defined-risk bears survived the surprise.',
  },
  {
    id: 'jh-2022-08', ticker: 'SPX', title: 'Powell promises pain', date: 'Aug 2022',
    summary: 'A short, hawkish Jackson Hole speech warned of "some pain"; the S&P 500 fell ≈ 3.4% that day and kept falling.',
    terms: ['fomc', 'collar', 'protective-put', 'roll', 'trend'], tags: ['macro', 'fed', 'event'],
    checkpoints: [
      { label: 'Before the speech', date: '2022-08-25', context: 'SPX ≈ 4,199 after a summer rally. VIX ≈ 21.8. Powell speaks Friday morning at Jackson Hole.',
        step: s('You want to protect a stock portfolio through the speech at low net cost. Which structure?', [['collar', 'Collar: buy a put, sell an OTM call'], ['calls', 'Buy calls in case the speech is dovish'], ['none', 'No hedge, the summer trend is up']], 'collar', 'A collar pays for most of the put with the call premium. You give up some upside but get a floor over the event.') },
      { label: 'Speech day', date: '2022-08-26', context: 'Powell warned of restrictive policy for some time and "some pain". SPX closed ≈ 4,058 (−3.4%). Dow −1,008 points. VIX ≈ 25.6.',
        step: s('Your collar\'s put is now close to the money. If SPX falls further, your loss is…', [['floor', 'Limited below the put strike'], ['open', 'Open-ended, a collar only reduces cost']], 'floor', 'The long put sets a floor. The short call only limits upside, which did not matter on this day.') },
      { label: 'Ten days later', date: '2022-09-06', context: 'SPX ≈ 3,908, about 7% below Aug 25. VIX ≈ 26.9. The collar\'s put is ITM; its call is far OTM.',
        step: s('You still want protection for the next month. Best adjustment?', [['roll', 'Take the put gain and roll the collar down and out'], ['drop', 'Remove all hedges, the drop is done']], 'roll', 'Rolling banks the gain and resets the floor near the new price. The trend was still down a month later.') },
    ],
    outcome: 'A speech, not a rate decision, set the [[trend]]: SPX fell ≈ 13% in a month. A [[collar]] gave a cheap floor, and a [[roll]] kept it near the price.',
  },
  {
    id: 'fomc-2024-12', ticker: 'VIX', title: 'The hawkish cut', date: 'Dec 2024',
    summary: 'The Fed cut rates but signaled only two cuts in 2025; VIX jumped ≈ 74% in one day, its second-largest % rise on record.',
    terms: ['fomc', 'vix', 'term-structure', 'contango', 'profit-target'], tags: ['macro', 'fed', 'volatility'],
    checkpoints: [
      { label: 'Day before FOMC', date: '2024-12-17', context: 'SPX ≈ 6,051 near a record. VIX ≈ 15.9. A 25bp cut is fully expected. At low VIX, futures usually trade above spot (contango).',
        step: s('You want cheap protection over the FOMC day. Best idea?', [['small', 'Small SPX put spread or VIX call spread'], ['big', 'Large VIX calls: VIX is cheap'], ['none', 'No hedge: the cut is priced in']], 'small', 'The decision was priced, but the projections were not. Low VIX makes a small, defined hedge cheap; size it as insurance.') },
      { label: 'FOMC day', date: '2024-12-18', context: 'Cut to 4.25–4.50%, but projections showed two 2025 cuts, down from four. SPX ≈ 5,872 (−2.9%). VIX ≈ 27.6 (+74%).',
        step: s('Your VIX call spread is near max value. Next?', [['take', 'Take most of the profit now'], ['wait', 'Hold for a bigger spike']], 'take', 'VIX spikes mean-revert fast, and VIX options follow the futures, not spot. Use a profit target for volatility trades.') },
      { label: 'Christmas Eve', date: '2024-12-24', context: 'VIX ≈ 14.3, back below its pre-FOMC level. SPX recovered part of the loss.',
        step: s('What does the fast fade say about long VIX trades?', [['short', 'They are short-lived: plan exits before entry'], ['long', 'Hold them for months to wait for the next spike']], 'short', 'In contango, long VIX exposure decays over time. The payoff from a spike must be taken quickly.') },
    ],
    outcome: 'The new projections, not the cut, caused the shock. The VIX spike faded within a week; a [[profit-target]] mattered more than the forecast.',
  },
  {
    id: 'fed-2020-03', ticker: 'SPX', title: 'The emergency cut', date: 'Mar 2020',
    summary: 'The Fed cut 50bp between meetings, its first emergency cut since 2008; stocks fell anyway and crashed 7.6% six days later.',
    terms: ['fomc', 'bull-put-spread', 'max-loss', 'tail-risk', 'vix'], tags: ['macro', 'fed', 'crash'],
    checkpoints: [
      { label: 'Relief bounce', date: '2020-03-02', context: 'SPX ≈ 3,090 (+4.6%) after a week of heavy losses. VIX ≈ 33.4. Markets expect Fed help.',
        step: s('Put premium is rich at VIX ≈ 33. You want to sell it. Safer structure?', [['bps', 'Small bull put spread'], ['nsp', 'Naked short puts, large size']], 'bps', 'High IV pays more because the risk is high. The long put caps the loss if the crash continues.') },
      { label: 'Emergency cut', date: '2020-03-03', context: 'Fed cut 50bp to 1.00–1.25% at 10:00 ET, between meetings. Stocks jumped, then SPX closed ≈ 3,003 (−2.8%). VIX ≈ 36.8.',
        step: s('What did an emergency cut signal to the market?', [['fear', 'The Fed sees serious risk; volatility can stay high'], ['clear', 'All clear: the Fed has solved the problem']], 'fear', 'A surprise policy move tells you policymakers are worried. It does not create a floor under prices.') },
      { label: 'Circuit breaker', date: '2020-03-09', context: 'SPX −7.6% to ≈ 2,747. A 15-minute market-wide halt at the open. VIX ≈ 54.5.',
        step: s('Your bull put spread is now at full loss. Compare it with naked puts:', [['cap', 'The spread lost its known max; naked puts kept losing'], ['same', 'Both lost the same amount']], 'cap', 'The spread loss stopped at width minus credit. Naked puts lost on each further point, with margin calls.') },
    ],
    outcome: 'Policy help did not stop a [[tail-risk]] crash. Premium sellers with a known [[max-loss]] survived; naked put sellers did not.',
  },
  {
    id: 'tlt-2013-05', ticker: 'TLT', title: 'The taper tantrum', date: 'May–Jun 2013',
    summary: 'Bernanke hinted at slower bond buying; the 10-year yield rose from ≈ 1.6% to ≈ 2.7% and TLT fell ≈ 14%.',
    terms: ['fomc', 'protective-put', 'risk-free-rate', 'iv', 'bull-call-spread'], tags: ['rates', 'fed', 'bonds'],
    checkpoints: [
      { label: 'Calm bonds', date: '2013-05-01', context: 'TLT ≈ $124. 10-year yield ≈ 1.63%, near record lows. Fed buys $85B of bonds a month. TLT IV low.',
        step: s('You hold a large TLT position as your "safe" asset. Best risk step?', [['put', 'Buy a cheap OTM TLT put'], ['none', 'No hedge: bonds are safe'], ['cc', 'Sell calls for extra income only']], 'put', 'Long bonds have large duration risk. Low IV makes a protective put cheap when nobody expects a move.') },
      { label: 'Bernanke testimony', date: '2013-05-22', context: 'Bernanke: the Fed could slow purchases "in the next few meetings". 10-year yield above 2% for the first time since March. TLT ≈ $116.',
        step: s('A friend thinks the sell-off is overdone and wants a bullish TLT bet. Better structure?', [['bcs', 'Bull call spread with a few months to expiry'], ['wk', 'Weekly OTM calls for a fast bounce']], 'bcs', 'Fed guidance can move rates for weeks. More time and a spread reduce the cost of being early.') },
      { label: 'After the press conference', date: '2013-06-21', context: 'June 19: Bernanke said purchases could slow later in 2013 and end mid-2014. 10-year ≈ 2.51%. TLT ≈ $108.',
        step: s('Lesson from a "safe" bond fund falling ≈ 13% in seven weeks?', [['dur', 'Rate shocks hit long bonds hard; hedge and size them too'], ['safe', 'Bonds cannot lose much, this was a one-off']], 'dur', 'A 1-point rise in long yields is a large price loss for long-duration bonds. Safe from default is not safe from price moves.') },
    ],
    outcome: 'Guidance alone moved the [[risk-free-rate]] by about a point. The cheap [[protective-put]] bought in calm conditions was the best-value hedge.',
  },
  {
    id: 'brexit-2016-06', ticker: 'FXB', title: 'The Brexit vote', date: 'Jun 2016',
    summary: 'The UK voted 51.9% to leave the EU; the pound hit its lowest level since 1985 and the S&P 500 fell ≈ 3.6%.',
    terms: ['gap', 'tail-risk', 'iv-crush', 'correlation', 'vix'], tags: ['macro', 'fx', 'event'],
    checkpoints: [
      { label: 'Vote day', date: '2016-06-23', context: 'Polls and markets leaned to Remain. FXB ≈ $145.5 after a rally. SPX ≈ 2,113 (+1.3%). VIX ≈ 17.3. Results arrive overnight.',
        step: s('Options price a big pound move. You think Remain wins. Best trade?', [['def', 'Small defined-risk position, or no trade'], ['ns', 'Sell a naked FXB strangle for the rich premium']], 'def', 'A vote is a binary event. Selling naked premium into it risks a large gap you cannot exit overnight.') },
      { label: 'Leave wins', date: '2016-06-24', context: 'Leave 51.9%. Pound to its lowest since 1985 overnight. FXB ≈ $133.3 (−8.4%). SPX ≈ 2,037 (−3.6%). VIX ≈ 25.8.',
        step: s('A UK vote moved US stocks 3.6%. What does that mean for hedging?', [['corr', 'In a shock, correlations rise; a local event can hit all markets'], ['local', 'US portfolios do not need to care about UK events']], 'corr', 'Global risk-off selling moves many assets together. An index hedge helped even for a US-only portfolio.') },
      { label: 'Fast fade', date: '2016-06-28', context: 'SPX ≈ 2,036 after ≈ 2,001 on Jun 27. VIX ≈ 18.8. FXB still ≈ $130.6.',
        step: s('VIX is almost back to pre-vote levels, but the pound is not. Why?', [['fade', 'Equity fear faded fast; the currency repriced for the long term'], ['same', 'Both markets always recover together']], 'fade', 'Event volatility often collapses after the result. A real economic change can still leave a lasting price move.') },
    ],
    outcome: 'An overnight [[gap]] on a binary vote. US stocks fell with the pound through [[correlation]], then [[iv-crush]] followed; the pound stayed low.',
  },
  {
    id: 'election-2016-11', ticker: 'SPY', title: 'Election night whiplash', date: 'Nov 2016',
    summary: 'S&P futures fell 5% to limit down overnight as results came in; the next day the S&P 500 closed ≈ 1.1% higher.',
    terms: ['straddle', 'breakeven', 'iv-crush', 'expected-move', 'gap'], tags: ['macro', 'election', 'event'],
    checkpoints: [
      { label: 'Election day', date: '2016-11-08', context: 'SPX ≈ 2,140. VIX ≈ 18.7, elevated for the election. Most polls favored Clinton.',
        step: s('You buy an SPY straddle to trade the result. What must happen for it to profit?', [['big', 'A move larger than the premium paid'], ['any', 'Any move, up or down'], ['up', 'Only a rally']], 'big', 'A straddle breaks even only after the move pays back both premiums. The expected move is already in the price.') },
      { label: 'Overnight', date: '2016-11-08', context: 'Around midnight ET, S&P futures fell 5% to limit down; Dow futures fell more than 800 points. Options on SPY do not trade overnight.',
        step: s('Your straddle looks like a big winner overnight. Can you lock it in?', [['no', 'No: you must wait for the open, so plan exits in advance'], ['yes', 'Yes: options trade all night like futures']], 'no', 'Options in regular hours cannot react to an overnight move. The price at the open is what counts.') },
      { label: 'Next close', date: '2016-11-09', context: 'SPX ≈ 2,163 (+1.1%) after a reversal. VIX ≈ 14.4 (−23%).',
        step: s('The straddle lost money despite a wild night. Why?', [['crush', 'The close move was small and IV collapsed'], ['luck', 'Bad luck only, the trade was correct']], 'crush', 'The night\'s −5% did not last. A small close move plus [[iv-crush]] puts a long straddle below breakeven.') },
    ],
    outcome: 'A limit-down overnight move that vanished by the close. Long straddles lost to [[iv-crush]]; the move that counted was the one you could trade.',
  },
  {
    id: 'election-2024-11', ticker: 'IWM', title: 'The small-cap election pop', date: 'Nov 2024',
    summary: 'After the election result, IWM jumped ≈ 5.8% and TSLA ≈ 15% in one day as VIX dropped ≈ 21%.',
    terms: ['bull-call-spread', 'profit-target', 'iv', 'gap', 'trend'], tags: ['macro', 'election', 'small-caps'],
    checkpoints: [
      { label: 'Election day', date: '2024-11-05', context: 'IWM ≈ $224. VIX ≈ 20.5. IWM options price a large election move.',
        step: s('You expect small caps to rally on one outcome. IV is high. Best structure?', [['bcs', 'Bull call spread, small size'], ['otm', 'Many short-dated OTM calls']], 'bcs', 'Selling the upper call offsets the high event IV. Outright calls lose to IV crush unless the move is very large.') },
      { label: 'Day after', date: '2024-11-06', context: 'IWM ≈ $237 (+5.8%). TSLA ≈ $289 (+14.8%). VIX ≈ 16.3 (−21%).',
        step: s('Your call spread is near max value on day one. Next?', [['take', 'Close it at your profit target'], ['hold', 'Hold to expiry for the last part']], 'take', 'Most of the spread value came in one day. The remaining gain is small and a reversal would cost much more.') },
      { label: 'The chase', date: '2024-11-11', context: 'IWM ≈ $242. TSLA ≈ $350, about 39% above Nov 5. Next day TSLA fell ≈ 6% and IWM ≈ 1.8%.',
        step: s('You missed TSLA and want to buy short-dated calls at high IV. Lesson?', [['chase', 'Chasing a stretched move with expensive calls is poor risk/reward'], ['go', 'Strong trends always continue, so buy']], 'chase', 'After a large run, IV and price both have room to fall. Wait for a plan with defined risk and small size.') },
    ],
    outcome: 'An election [[gap]] that rewarded a planned spread. Taking profit at the [[profit-target]] beat chasing the [[trend]] at high [[iv]].',
  },
  {
    id: 'china-2015-08', ticker: 'SPY', title: 'The yuan shock and flash crash', date: 'Aug 2015',
    summary: 'China devalued the yuan; two weeks later the Dow fell 1,089 points at the open and VIX hit ≈ 53 intraday.',
    terms: ['vix', 'protective-put', 'limit-order', 'slippage', 'liquidity'], tags: ['macro', 'crash', 'china'],
    checkpoints: [
      { label: 'Devaluation', date: '2015-08-11', context: 'China cut the yuan reference rate by 1.9%, the biggest drop since 1994. SPX ≈ 2,084 (−1.0%). VIX ≈ 13.7.',
        step: s('A global shock, but VIX is still ≈ 14. What does that mean for hedging?', [['cheap', 'Protection is still cheap: buy small SPY puts'], ['late', 'Too late to hedge, wait for the drop']], 'cheap', 'The warning came while IV was low. Hedges cost least before the market reacts in full.') },
      { label: 'Flash crash', date: '2015-08-24', context: 'Dow −1,089 at the open. SPY low ≈ $182.4 vs ≈ $197.8 Friday close. Many stocks and ETFs halted. VIX ≈ 53 intraday, closed ≈ 40.7.',
        step: s('A trader had stop-market orders on ETFs. What was the risk at the open?', [['slip', 'Fills far below the stop in a thin market'], ['fine', 'Stops fill at the stop price']], 'slip', 'In a disorderly open, liquidity vanishes. Stop-market orders can fill at very poor prices; limit orders cap the price.') },
      { label: 'Rebound', date: '2015-08-27', context: 'SPX ≈ 1,988 after +3.9% and +2.4% days. VIX ≈ 26.1.',
        step: s('Your SPY puts from Aug 11 gained a lot. Best next step?', [['take', 'Take profit on part; keep some protection'], ['add', 'Buy more puts now']], 'take', 'IV was still high, which kept put prices rich. Banking part locks in the hedge gain if the rebound continues.') },
    ],
    outcome: 'A slow warning, then a sudden crash. Cheap [[protective-put]] hedges worked; stop-market orders suffered [[slippage]] when [[liquidity]] vanished.',
  },
  {
    id: 'downgrade-2011-08', ticker: 'SPX', title: 'The US credit downgrade', date: 'Aug 2011',
    summary: 'S&P cut the US rating from AAA to AA+ on a Friday night; on Monday the S&P 500 fell ≈ 6.7%.',
    terms: ['gap', 'vix', 'position-sizing', 'credit-spread', 'fomc'], tags: ['macro', 'crash', 'credit'],
    checkpoints: [
      { label: 'Friday close', date: '2011-08-05', context: 'SPX ≈ 1,199 after −4.8% on Thursday. VIX ≈ 32. A downgrade is rumored. S&P announces AAA → AA+ after the close.',
        step: s('You are short SPX puts going into the weekend. Best move?', [['cut', 'Reduce or hedge before the close'], ['keep', 'Keep them for the weekend theta']], 'cut', 'News can land while the market is closed. Two days of theta are small compared with a Monday gap.') },
      { label: 'Black Monday', date: '2011-08-08', context: 'SPX −6.7% to ≈ 1,119. VIX closed ≈ 48.',
        step: s('Put premium is very rich. You want to sell some. How?', [['small', 'Small, defined-risk credit spreads'], ['big', 'Large naked puts, VIX this high must fall']], 'small', 'High VIX means big premium and big moves. Size for daily swings of 4% or more.') },
      { label: 'Whipsaw', date: '2011-08-09', context: 'FOMC: rates near zero "at least through mid-2013". SPX +4.7% to ≈ 1,173. Next day −4.4%, then +4.6%.',
        step: s('Four days, four moves over 4%. What decides survival here?', [['size', 'Position size and defined risk'], ['call', 'Calling each day\'s direction right']], 'size', 'Nobody times swings like these. Small size and capped loss let you stay in the game.') },
    ],
    outcome: 'A weekend [[gap]] then a high-[[vix]] whipsaw. Careful [[position-sizing]] mattered more than direction.',
  },
  {
    id: 'snb-2015-01', ticker: 'FXF', title: 'The Swiss franc floor breaks', date: 'Jan 2015',
    summary: 'The SNB dropped its 1.20 EUR/CHF floor without warning; the franc jumped up to ≈ 30% in minutes and FXF closed ≈ 17% higher.',
    terms: ['tail-risk', 'gap', 'naked-call', 'stop-loss', 'iv'], tags: ['fx', 'central-bank', 'crash'],
    checkpoints: [
      { label: 'The floor holds', date: '2015-01-14', context: 'FXF ≈ $95.8. The SNB had defended the 1.20 EUR/CHF floor since 2011. Franc IV very low.',
        step: s('A peg keeps the franc calm. You want to sell FXF calls for income. Safer choice?', [['wing', 'Call spread, or no trade'], ['naked', 'Naked calls: the central bank guarantees the floor']], 'wing', 'A peg suppresses volatility until it breaks. Low IV then hides a large tail risk, so cap the loss.') },
      { label: 'Floor dropped', date: '2015-01-15', context: 'SNB ends the floor and cuts its rate to −0.75%. Franc up to ≈ 30% in minutes. FXF opened ≈ $111, closed ≈ $112.2 (+17%).',
        step: s('A trader had a stop-loss on short franc positions. What happened?', [['gap', 'It filled far beyond the stop, or not at all'], ['stop', 'It filled at the stop price']], 'gap', 'A policy surprise gaps the price. Only an option you hold caps the loss in a gap.') },
      { label: 'Day after', date: '2015-01-16', context: 'FXF ≈ $113.8. Franc IV far higher than before. Some FX brokers reported large client losses.',
        step: s('A trader who held cheap FXF calls now has a big gain at high IV. Next?', [['take', 'Take most of the profit while IV is high'], ['hold', 'Hold for another 30% move']], 'take', 'The shock already happened. High IV makes the calls worth more now than after volatility settles.') },
    ],
    outcome: 'A pegged market is calm until it is not. [[naked-call]] sellers and [[stop-loss]] users were hit by the [[gap]]; cheap long calls paid out.',
  },
  {
    id: 'tariffs-2025-04', ticker: 'SPY', title: 'Liberation Day tariffs', date: 'Apr 2025',
    summary: 'Broad US tariffs sent the S&P 500 down ≈ 10.5% in two days; a 90-day pause then gave a ≈ 9.5% one-day rally.',
    terms: ['vix', 'bear-put-spread', 'vega', 'gap', 'tail-risk'], tags: ['macro', 'tariffs', 'crash'],
    checkpoints: [
      { label: 'Announcement', date: '2025-04-02', context: 'SPY ≈ $564.5. VIX ≈ 21.5. Tariff plan announced after the close, with a 10% baseline and higher rates for many countries.',
        step: s('The details came after the bell. What risk does a long stock portfolio face?', [['gap', 'An overnight gap you cannot trade through'], ['none', 'None until the tariffs start']], 'gap', 'Policy news after the close moves prices at the next open. Hedges must be in place before the news.') },
      { label: 'Peak stress', date: '2025-04-08', context: 'SPY ≈ $496.5. SPX −4.8% Apr 3 and −6.0% Apr 4. VIX hit ≈ 60 intraday Apr 7 and closed ≈ 52.3 Apr 8.',
        step: s('You want bearish exposure with VIX ≈ 52. Best structure?', [['bps', 'Bear put spread: sell a lower put against it'], ['put', 'Outright ATM puts at any price']], 'bps', 'At very high IV, outright puts carry a large vega cost. The short leg sells part of that rich IV back.') },
      { label: 'The pause', date: '2025-04-09', context: '90-day pause on most new tariffs. SPX +9.5% to ≈ 5,457, its best day since 2008. SPY ≈ $548.6. VIX ≈ 33.6 (−36%).',
        step: s('Bearish positions lost on price and IV in hours. Lesson about policy-driven markets?', [['both', 'A policy reversal can gap prices either way; cap the loss'], ['once', 'Policy only moves markets one way']], 'both', 'Headline risk goes both ways. The put spread loss was capped; outright puts lost more value as IV collapsed.') },
    ],
    outcome: 'A policy [[tail-risk]] in both directions. Spreads limited the [[vega]] cost at peak [[vix]], and the reversal [[gap]] punished uncapped bets.',
  },
  {
    id: 'nvda-2025-01', ticker: 'NVDA', title: 'The DeepSeek shock', date: 'Jan 2025',
    summary: 'A low-cost Chinese AI model raised doubts about AI chip demand; NVDA fell ≈ 17% and lost ≈ $589B in one day, a record.',
    terms: ['collar', 'gap', 'cash-secured-put', 'iv', 'position-sizing'], tags: ['tech', 'gap', 'ai'],
    checkpoints: [
      { label: 'Friday', date: '2025-01-24', context: 'NVDA ≈ $142.6. DeepSeek\'s new model gains attention over the weekend. NVDA is a large share of many portfolios.',
        step: s('NVDA is 30% of your portfolio. Cheapest way to cap the downside?', [['collar', 'Collar: buy a put, sell an OTM call'], ['none', 'No hedge, AI demand is certain'], ['stop', 'Rely on a stop-loss']], 'collar', 'One stock at 30% is concentration risk. A collar sets a floor at low net cost; a stop cannot protect against a gap.') },
      { label: 'Record loss', date: '2025-01-27', context: 'NVDA opened ≈ $124.8, closed ≈ $118.4 (−17%), ≈ $589B of market value lost. Nasdaq −3.1%. IV jumped.',
        step: s('You want to buy NVDA lower and IV is high. Which approach?', [['csp', 'Cash-secured put at a lower strike, sized for assignment'], ['margin', 'Buy shares on margin, all in']], 'csp', 'High IV pays you to wait for a lower price. Size it so assignment is a position you want.') },
      { label: 'Rebound and retest', date: '2025-02-03', context: 'Jan 28: NVDA +8.9% to ≈ $129.0. Feb 3: ≈ $116.7, below the Jan 27 close.',
        step: s('Lesson from the +8.9% bounce and the later retest?', [['plan', 'After a shock, volatility stays high; keep size small'], ['bottom', 'The first bounce always marks the bottom']], 'plan', 'Shocks leave large swings both ways for days. Small size and defined plans beat guessing the bottom.') },
    ],
    outcome: 'A single-stock [[gap]] in a market leader. A [[collar]] limited the loss; rich [[iv]] after the drop favored a sized [[cash-secured-put]] over chasing.',
  },
  {
    id: 'gilt-2022-09', ticker: 'FXB', title: 'The UK gilt crisis', date: 'Sep 2022',
    summary: 'An unfunded UK tax-cut budget crashed gilts and sent the pound to a record low; the Bank of England had to buy long gilts.',
    terms: ['tail-risk', 'liquidity', 'protective-put', 'profit-target', 'iv'], tags: ['macro', 'fx', 'bonds'],
    checkpoints: [
      { label: 'Mini-budget', date: '2022-09-23', context: 'Largest UK tax cuts in about 50 years, without funding plans. FXB ≈ $104.5 (−3.4%). Pound at 1985 lows. Gilt yields jump.',
        step: s('You hold UK assets priced in pounds. Best hedge?', [['put', 'Buy FXB puts or a put spread'], ['none', 'No hedge, the pound cannot fall further'], ['cc', 'Sell FXB covered calls only']], 'put', 'A put sets a floor on the currency risk. A covered call gives only a small cushion in a fast fall.') },
      { label: 'Record low', date: '2022-09-26', context: 'Pound hit a record low ≈ $1.03 in Asian trading. FXB ≈ $102.8. Long gilt yields kept rising; pension LDI funds faced collateral calls.',
        step: s('Why did gilts keep falling as yields rose?', [['forced', 'Leveraged funds had to sell gilts to meet collateral calls'], ['value', 'Investors saw no value at higher yields']], 'forced', 'Forced selling feeds itself: lower prices create more calls and more selling. Liquidity disappears in such a spiral.') },
      { label: 'BoE steps in', date: '2022-09-28', context: 'BoE begins temporary purchases of gilts over 20 years, up to £5bn per auction. FXB ≈ $104.6, then ≈ $107.3 by Sep 30.',
        step: s('Your FXB puts were deep ITM on Sep 26. A central bank now acts. Next?', [['take', 'Take profit at your target before policy reverses the move'], ['hold', 'Hold, the crisis must get worse']], 'take', 'Central banks can stop a spiral fast. A profit target set in advance locks in a hedge gain before the snap-back.') },
    ],
    outcome: 'A [[liquidity]] spiral in a core bond market. FXB puts paid at the low; a [[profit-target]] mattered once the Bank of England acted.',
  },
]
