import type { Term } from '../shared/types'

// [id, name, short, tags, related, formula?, example?]
export type T = [string, string, string, string[], string[], string?, string?]

const raw: T[] = [
  ['option', 'Option', 'A contract giving the right, not the obligation, to buy or sell an underlying at a set price before a set date.', ['basics'], ['call', 'put', 'underlying', 'strike', 'expiration']],
  ['call', 'Call option', 'Right to BUY the underlying at the strike. Gains when price rises.', ['basics', 'bullish'], ['put', 'strike', 'premium', 'long-call', 'delta'], 'Payoff = max(S − K, 0) − premium', 'Buy a $100 call for $3: profit above $103 at expiry.'],
  ['put', 'Put option', 'Right to SELL the underlying at the strike. Gains when price falls.', ['basics', 'bearish'], ['call', 'strike', 'premium', 'long-put', 'protective-put'], 'Payoff = max(K − S, 0) − premium', 'Buy a $100 put for $2: profit below $98 at expiry.'],
  ['underlying', 'Underlying', 'The stock, ETF or index the option is written on.', ['basics'], ['option', 'spot']],
  ['spot', 'Spot price', 'Current market price of the underlying (S).', ['basics'], ['underlying', 'moneyness']],
  ['strike', 'Strike price', 'The fixed price (K) at which the option can be exercised.', ['basics'], ['moneyness', 'itm', 'otm', 'atm']],
  ['premium', 'Premium', 'The price paid for an option. Premium = intrinsic + extrinsic value.', ['basics', 'pricing'], ['intrinsic', 'extrinsic', 'iv'], 'Premium = intrinsic + extrinsic'],
  ['expiration', 'Expiration', 'The last day the option exists. After it, the option settles or expires worthless.', ['basics', 'time'], ['theta', 'dte']],
  ['dte', 'Days to expiration (DTE)', 'Calendar days left until expiry. Fewer DTE means faster time decay.', ['time'], ['theta', 'expiration']],
  ['multiplier', 'Contract multiplier', 'One US equity option controls 100 shares. A $2.50 quote costs $250.', ['basics'], ['premium']],
  ['moneyness', 'Moneyness', 'Where the strike sits relative to spot: ITM, ATM or OTM.', ['basics'], ['itm', 'atm', 'otm']],
  ['itm', 'In the money (ITM)', 'Has intrinsic value. Call: S > K. Put: S < K.', ['basics'], ['moneyness', 'intrinsic', 'delta']],
  ['atm', 'At the money (ATM)', 'Strike ≈ spot. Highest extrinsic value, gamma and theta.', ['basics'], ['moneyness', 'gamma', 'straddle']],
  ['otm', 'Out of the money (OTM)', 'No intrinsic value. Call: S < K. Put: S > K. Pure time + volatility value.', ['basics'], ['moneyness', 'extrinsic']],
  ['intrinsic', 'Intrinsic value', 'What the option is worth if exercised now.', ['pricing'], ['extrinsic', 'itm', 'premium'], 'Call: max(S−K,0)  Put: max(K−S,0)'],
  ['extrinsic', 'Extrinsic (time) value', 'Premium above intrinsic. Driven by time and implied volatility. Decays to zero at expiry.', ['pricing', 'time'], ['intrinsic', 'theta', 'iv']],
  ['exercise', 'Exercise', 'Using the right in the contract: buying (call) or selling (put) at the strike.', ['mechanics'], ['assignment', 'american']],
  ['assignment', 'Assignment', 'When a short option is exercised against you. You must deliver (short call) or buy (short put).', ['mechanics', 'risk'], ['exercise', 'pin-risk', 'cash-secured-put']],
  ['american', 'American style', 'Can be exercised any time before expiry. Most US single-stock options.', ['mechanics'], ['european', 'exercise']],
  ['european', 'European style', 'Exercisable only at expiry. Most index options like SPX.', ['mechanics'], ['american']],
  ['open-interest', 'Open interest', 'Number of contracts currently open. Signals liquidity and where positioning sits.', ['market'], ['volume', 'gamma-squeeze']],
  ['volume', 'Volume', 'Contracts traded today. Unusual volume can flag news or positioning.', ['market'], ['open-interest']],
  ['bid-ask', 'Bid–ask spread', 'Gap between best buy and sell quotes. Wide spreads are a hidden cost.', ['market', 'risk'], ['volume', 'open-interest']],
  ['iv', 'Implied volatility (IV)', 'The volatility the market is pricing into the option. Higher IV = more expensive options.', ['volatility', 'pricing'], ['vega', 'hv', 'iv-rank', 'iv-crush', 'black-scholes'], 'Solved from market price via Black-Scholes'],
  ['hv', 'Historical volatility (HV)', 'How much the stock actually moved, annualized. Compare to IV to judge if options are cheap or rich.', ['volatility'], ['iv']],
  ['iv-rank', 'IV Rank', 'Where today\'s IV sits in its 1-year range, 0–100. High = options relatively expensive.', ['volatility', 'indicator'], ['iv', 'credit-spread', 'iron-condor'], 'IVR = (IV − IVlow) / (IVhigh − IVlow) × 100'],
  ['iv-crush', 'IV crush', 'Sharp drop in IV after a known event (earnings), deflating option prices even if the stock moves.', ['volatility', 'events'], ['iv', 'earnings', 'vega', 'straddle']],
  ['vix', 'VIX', 'Index of 30-day implied volatility on the S&P 500. The market\'s "fear gauge".', ['volatility', 'market'], ['iv', 'skew']],
  ['skew', 'Volatility skew', 'IV differs by strike. Equity puts usually carry higher IV than calls (crash insurance demand).', ['volatility'], ['iv', 'put', 'vix']],
  ['expected-move', 'Expected move', 'The ±1σ range implied by option prices. ATM straddle ≈ expected move.', ['volatility', 'events'], ['straddle', 'iv', 'earnings'], 'EM ≈ S × IV × √(days/365)'],
  ['greeks', 'The Greeks', 'Sensitivities of option price to price, time, volatility and rates.', ['greeks'], ['delta', 'gamma', 'theta', 'vega', 'rho']],
  ['delta', 'Delta (Δ)', 'Price change per $1 move in the underlying. Also a rough probability of finishing ITM.', ['greeks'], ['gamma', 'itm', 'hedging'], 'Call 0…1, Put −1…0'],
  ['gamma', 'Gamma (Γ)', 'How fast delta changes per $1 move. Highest ATM near expiry.', ['greeks', 'risk'], ['delta', 'gamma-squeeze', 'atm']],
  ['theta', 'Theta (Θ)', 'Value lost per day from time decay. Buyers pay theta; sellers collect it.', ['greeks', 'time'], ['extrinsic', 'dte', 'credit-spread']],
  ['vega', 'Vega (ν)', 'Price change per 1-point change in IV. Long options are long vega.', ['greeks', 'volatility'], ['iv', 'iv-crush', 'calendar']],
  ['rho', 'Rho (ρ)', 'Price change per 1% change in interest rates. Matters more for long-dated options.', ['greeks'], ['leaps']],
  ['black-scholes', 'Black–Scholes model', 'Classic pricing model using S, K, time, rate and volatility.', ['pricing'], ['iv', 'greeks']],
  ['hedging', 'Delta hedging', 'Offsetting delta with stock so the position is neutral to small moves.', ['greeks', 'mechanics'], ['delta', 'gamma-squeeze']],
  ['breakeven', 'Breakeven', 'Underlying price at expiry where the trade neither gains nor loses.', ['strategy'], ['premium', 'max-loss'], 'Long call: K + premium. Long put: K − premium'],
  ['max-loss', 'Max loss', 'Worst-case loss. Defined for debit trades and spreads; can be unlimited for naked shorts.', ['risk'], ['max-profit', 'position-sizing']],
  ['max-profit', 'Max profit', 'Best-case gain of a structure. Capped for spreads and short options.', ['risk'], ['max-loss']],
  ['long-call', 'Long call', 'Buy a call. Bullish, defined risk, needs a move bigger than the premium.', ['strategy', 'bullish'], ['call', 'breakeven', 'theta']],
  ['long-put', 'Long put', 'Buy a put. Bearish or protective, defined risk.', ['strategy', 'bearish'], ['put', 'protective-put']],
  ['covered-call', 'Covered call', 'Own 100 shares, sell a call against them. Earn income, cap upside.', ['strategy', 'income'], ['call', 'theta', 'assignment']],
  ['cash-secured-put', 'Cash-secured put', 'Sell a put with cash set aside to buy shares if assigned. Get paid to wait for a lower price.', ['strategy', 'income', 'bullish'], ['put', 'assignment', 'theta']],
  ['protective-put', 'Protective put', 'Own shares plus buy a put: insurance against a drop.', ['strategy', 'hedge'], ['put', 'skew']],
  ['collar', 'Collar', 'Own shares, buy a put, sell a call to pay for it. Bounded outcome.', ['strategy', 'hedge'], ['protective-put', 'covered-call']],
  ['vertical', 'Vertical spread', 'Buy and sell same-type options, same expiry, different strikes. Defined risk and reward.', ['strategy', 'spread'], ['bull-call-spread', 'bear-put-spread', 'credit-spread', 'debit-spread']],
  ['debit-spread', 'Debit spread', 'Pay to open. Profit if the move happens. Lower cost and vega than a single long option.', ['strategy', 'spread'], ['vertical', 'bull-call-spread']],
  ['credit-spread', 'Credit spread', 'Get paid to open. Profit if price stays away from the short strike. Benefits from theta and falling IV.', ['strategy', 'spread', 'income'], ['vertical', 'iv-rank', 'theta']],
  ['bull-call-spread', 'Bull call spread', 'Long lower call + short higher call. Moderately bullish, defined risk.', ['strategy', 'spread', 'bullish'], ['vertical', 'debit-spread']],
  ['bear-put-spread', 'Bear put spread', 'Long higher put + short lower put. Moderately bearish, defined risk.', ['strategy', 'spread', 'bearish'], ['vertical', 'debit-spread']],
  ['straddle', 'Straddle', 'Call + put at the same strike. Long = bet on a big move either way; short = bet on calm.', ['strategy', 'volatility'], ['strangle', 'expected-move', 'iv-crush']],
  ['strangle', 'Strangle', 'OTM call + OTM put. Cheaper than a straddle, needs a bigger move.', ['strategy', 'volatility'], ['straddle', 'iron-condor']],
  ['iron-condor', 'Iron condor', 'Short OTM put spread + short OTM call spread. Profit if price stays in a range. Defined risk.', ['strategy', 'spread', 'income', 'neutral'], ['credit-spread', 'strangle', 'iv-rank']],
  ['butterfly', 'Butterfly', '1 long low, 2 short middle, 1 long high strike. Cheap bet on price pinning near the middle.', ['strategy', 'neutral'], ['vertical', 'pin-risk']],
  ['calendar', 'Calendar spread', 'Sell near-term, buy longer-term option at the same strike. Profits from faster near-term decay and IV term structure.', ['strategy', 'time', 'volatility'], ['theta', 'vega']],
  ['leaps', 'LEAPS', 'Long-dated options (over 1 year). Behave more like stock, sensitive to rho and vega.', ['strategy', 'time'], ['rho', 'long-call']],
  ['roll', 'Rolling', 'Close a position and open a similar one at a different strike or expiry.', ['management'], ['assignment', 'credit-spread']],
  ['pin-risk', 'Pin risk', 'Uncertainty about assignment when price closes right at a short strike on expiry.', ['management', 'risk'], ['assignment', 'butterfly']],
  ['gamma-squeeze', 'Gamma squeeze', 'Dealers short calls buy stock to hedge as price rises, pushing price higher in a loop.', ['market', 'risk'], ['gamma', 'hedging', 'open-interest']],
  ['earnings', 'Earnings event', 'Scheduled report that drives a jump in price and IV, then IV crush.', ['events'], ['iv-crush', 'expected-move']],
  ['position-sizing', 'Position sizing', 'Risking a small, fixed % of the account per trade (often 1–5%) so one loss can\'t sink you.', ['management', 'risk'], ['max-loss']],
  ['rsi', 'RSI', 'Relative Strength Index, 0–100 momentum oscillator. Above 70 = overbought, below 30 = oversold.', ['indicator'], ['moving-average']],
  ['moving-average', 'Moving average', 'Average price over N days (e.g. 50/200). Price above = uptrend context.', ['indicator'], ['rsi']],
]

import { RAW_MORE } from './terms_more'

export const TERMS: Term[] = [...raw, ...RAW_MORE].map(([id, name, short, tags, related, formula, example]) => ({ id, name, short, tags, related, formula, example }))
export const TERM_MAP: Record<string, Term> = Object.fromEntries(TERMS.map((t) => [t.id, t]))
